/**
 * This class is generated by jOOQ
 */
package cn.kee.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import cn.kee.model.tables.Addresslibrary;
import cn.kee.model.tables.Businesslibrary;
import cn.kee.model.tables.Center;
import cn.kee.model.tables.Client;
import cn.kee.model.tables.Coupon;
import cn.kee.model.tables.Databasechangelog;
import cn.kee.model.tables.Databasechangeloglock;
import cn.kee.model.tables.Evaluation;
import cn.kee.model.tables.Expresstemplate;
import cn.kee.model.tables.Forwardcompany;
import cn.kee.model.tables.Imomessage;
import cn.kee.model.tables.Logisticsdata;
import cn.kee.model.tables.Message;
import cn.kee.model.tables.Note;
import cn.kee.model.tables.Order;
import cn.kee.model.tables.Permission;
import cn.kee.model.tables.Relatedinfo;
import cn.kee.model.tables.Relation;
import cn.kee.model.tables.Role;
import cn.kee.model.tables.Rolepermission;
import cn.kee.model.tables.Shop;
import cn.kee.model.tables.Staff;
import cn.kee.model.tables.Staffpermission;
import cn.kee.model.tables.Sysexpresstemplate;
import cn.kee.model.tables.Timeserver;
import cn.kee.model.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ewp extends SchemaImpl {

	private static final long serialVersionUID = 690157743;

	/**
	 * The reference instance of <code>ewp</code>
	 */
	public static final Ewp EWP = new Ewp();

	/**
	 * No further instances allowed
	 */
	private Ewp() {
		super("ewp");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Addresslibrary.ADDRESSLIBRARY,
			Businesslibrary.BUSINESSLIBRARY,
			Center.CENTER,
			Client.CLIENT,
			Coupon.COUPON,
			Databasechangelog.DATABASECHANGELOG,
			Databasechangeloglock.DATABASECHANGELOGLOCK,
			Evaluation.EVALUATION,
			Expresstemplate.EXPRESSTEMPLATE,
			Forwardcompany.FORWARDCOMPANY,
			Imomessage.IMOMESSAGE,
			Logisticsdata.LOGISTICSDATA,
			Message.MESSAGE,
			Note.NOTE,
			Order.ORDER,
			Permission.PERMISSION,
			Relatedinfo.RELATEDINFO,
			Relation.RELATION,
			Role.ROLE,
			Rolepermission.ROLEPERMISSION,
			Shop.SHOP,
			Staff.STAFF,
			Staffpermission.STAFFPERMISSION,
			Sysexpresstemplate.SYSEXPRESSTEMPLATE,
			Timeserver.TIMESERVER,
			User.USER);
	}
}
