/**
 * This class is generated by jOOQ
 */
package cn.kee.model;


import com.kee.model.tables.records.AddresslibraryRecord;
import com.kee.model.tables.records.BusinesslibraryRecord;
import com.kee.model.tables.records.CenterRecord;
import com.kee.model.tables.records.ClientRecord;
import com.kee.model.tables.records.CouponRecord;
import com.kee.model.tables.records.DatabasechangelogRecord;
import com.kee.model.tables.records.DatabasechangeloglockRecord;
import com.kee.model.tables.records.EvaluationRecord;
import com.kee.model.tables.records.ExpresstemplateRecord;
import com.kee.model.tables.records.ForwardcompanyRecord;
import com.kee.model.tables.records.ImomessageRecord;
import com.kee.model.tables.records.LogisticsdataRecord;
import com.kee.model.tables.records.MessageRecord;
import com.kee.model.tables.records.NoteRecord;
import com.kee.model.tables.records.OrderRecord;
import com.kee.model.tables.records.PermissionRecord;
import com.kee.model.tables.records.RelatedinfoRecord;
import com.kee.model.tables.records.RelationRecord;
import com.kee.model.tables.records.RoleRecord;
import com.kee.model.tables.records.RolepermissionRecord;
import com.kee.model.tables.records.ShopRecord;
import com.kee.model.tables.records.StaffRecord;
import com.kee.model.tables.records.StaffpermissionRecord;
import com.kee.model.tables.records.SysexpresstemplateRecord;
import com.kee.model.tables.records.TimeserverRecord;
import com.kee.model.tables.records.UserRecord;

import cn.kee.model.tables.Addresslibrary;
import cn.kee.model.tables.Businesslibrary;
import cn.kee.model.tables.Center;
import cn.kee.model.tables.Client;
import cn.kee.model.tables.Coupon;
import cn.kee.model.tables.Databasechangelog;
import cn.kee.model.tables.Databasechangeloglock;
import cn.kee.model.tables.Evaluation;
import cn.kee.model.tables.Expresstemplate;
import cn.kee.model.tables.Forwardcompany;
import cn.kee.model.tables.Imomessage;
import cn.kee.model.tables.Logisticsdata;
import cn.kee.model.tables.Message;
import cn.kee.model.tables.Note;
import cn.kee.model.tables.Order;
import cn.kee.model.tables.Permission;
import cn.kee.model.tables.Relatedinfo;
import cn.kee.model.tables.Relation;
import cn.kee.model.tables.Role;
import cn.kee.model.tables.Rolepermission;
import cn.kee.model.tables.Shop;
import cn.kee.model.tables.Staff;
import cn.kee.model.tables.Staffpermission;
import cn.kee.model.tables.Sysexpresstemplate;
import cn.kee.model.tables.Timeserver;
import cn.kee.model.tables.User;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>ewp</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AddresslibraryRecord> KEY_ADDRESSLIBRARY_PRIMARY = UniqueKeys0.KEY_ADDRESSLIBRARY_PRIMARY;
	public static final UniqueKey<BusinesslibraryRecord> KEY_BUSINESSLIBRARY_PRIMARY = UniqueKeys0.KEY_BUSINESSLIBRARY_PRIMARY;
	public static final UniqueKey<CenterRecord> KEY_CENTER_PRIMARY = UniqueKeys0.KEY_CENTER_PRIMARY;
	public static final UniqueKey<ClientRecord> KEY_CLIENT_PRIMARY = UniqueKeys0.KEY_CLIENT_PRIMARY;
	public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = UniqueKeys0.KEY_COUPON_PRIMARY;
	public static final UniqueKey<DatabasechangelogRecord> KEY_DATABASECHANGELOG_PRIMARY = UniqueKeys0.KEY_DATABASECHANGELOG_PRIMARY;
	public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = UniqueKeys0.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	public static final UniqueKey<EvaluationRecord> KEY_EVALUATION_PRIMARY = UniqueKeys0.KEY_EVALUATION_PRIMARY;
	public static final UniqueKey<ExpresstemplateRecord> KEY_EXPRESSTEMPLATE_PRIMARY = UniqueKeys0.KEY_EXPRESSTEMPLATE_PRIMARY;
	public static final UniqueKey<ForwardcompanyRecord> KEY_FORWARDCOMPANY_PRIMARY = UniqueKeys0.KEY_FORWARDCOMPANY_PRIMARY;
	public static final UniqueKey<ImomessageRecord> KEY_IMOMESSAGE_PRIMARY = UniqueKeys0.KEY_IMOMESSAGE_PRIMARY;
	public static final UniqueKey<LogisticsdataRecord> KEY_LOGISTICSDATA_PRIMARY = UniqueKeys0.KEY_LOGISTICSDATA_PRIMARY;
	public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = UniqueKeys0.KEY_MESSAGE_PRIMARY;
	public static final UniqueKey<NoteRecord> KEY_NOTE_PRIMARY = UniqueKeys0.KEY_NOTE_PRIMARY;
	public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = UniqueKeys0.KEY_ORDER_PRIMARY;
	public static final UniqueKey<PermissionRecord> KEY_PERMISSION_PRIMARY = UniqueKeys0.KEY_PERMISSION_PRIMARY;
	public static final UniqueKey<RelatedinfoRecord> KEY_RELATEDINFO_PRIMARY = UniqueKeys0.KEY_RELATEDINFO_PRIMARY;
	public static final UniqueKey<RelationRecord> KEY_RELATION_PRIMARY = UniqueKeys0.KEY_RELATION_PRIMARY;
	public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
	public static final UniqueKey<RolepermissionRecord> KEY_ROLEPERMISSION_PRIMARY = UniqueKeys0.KEY_ROLEPERMISSION_PRIMARY;
	public static final UniqueKey<ShopRecord> KEY_SHOP_PRIMARY = UniqueKeys0.KEY_SHOP_PRIMARY;
	public static final UniqueKey<StaffRecord> KEY_STAFF_PRIMARY = UniqueKeys0.KEY_STAFF_PRIMARY;
	public static final UniqueKey<StaffpermissionRecord> KEY_STAFFPERMISSION_PRIMARY = UniqueKeys0.KEY_STAFFPERMISSION_PRIMARY;
	public static final UniqueKey<SysexpresstemplateRecord> KEY_SYSEXPRESSTEMPLATE_PRIMARY = UniqueKeys0.KEY_SYSEXPRESSTEMPLATE_PRIMARY;
	public static final UniqueKey<TimeserverRecord> KEY_TIMESERVER_PRIMARY = UniqueKeys0.KEY_TIMESERVER_PRIMARY;
	public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AddresslibraryRecord> KEY_ADDRESSLIBRARY_PRIMARY = createUniqueKey(Addresslibrary.ADDRESSLIBRARY, Addresslibrary.ADDRESSLIBRARY.ADDRESSLIBRARYID);
		public static final UniqueKey<BusinesslibraryRecord> KEY_BUSINESSLIBRARY_PRIMARY = createUniqueKey(Businesslibrary.BUSINESSLIBRARY, Businesslibrary.BUSINESSLIBRARY.BUSINESSLIBRARYID);
		public static final UniqueKey<CenterRecord> KEY_CENTER_PRIMARY = createUniqueKey(Center.CENTER, Center.CENTER.CENTERID);
		public static final UniqueKey<ClientRecord> KEY_CLIENT_PRIMARY = createUniqueKey(Client.CLIENT, Client.CLIENT.CLIENTID);
		public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = createUniqueKey(Coupon.COUPON, Coupon.COUPON.COUPONID);
		public static final UniqueKey<DatabasechangelogRecord> KEY_DATABASECHANGELOG_PRIMARY = createUniqueKey(Databasechangelog.DATABASECHANGELOG, Databasechangelog.DATABASECHANGELOG.ID, Databasechangelog.DATABASECHANGELOG.AUTHOR, Databasechangelog.DATABASECHANGELOG.FILENAME);
		public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
		public static final UniqueKey<EvaluationRecord> KEY_EVALUATION_PRIMARY = createUniqueKey(Evaluation.EVALUATION, Evaluation.EVALUATION.EVALUATIONID);
		public static final UniqueKey<ExpresstemplateRecord> KEY_EXPRESSTEMPLATE_PRIMARY = createUniqueKey(Expresstemplate.EXPRESSTEMPLATE, Expresstemplate.EXPRESSTEMPLATE.ID);
		public static final UniqueKey<ForwardcompanyRecord> KEY_FORWARDCOMPANY_PRIMARY = createUniqueKey(Forwardcompany.FORWARDCOMPANY, Forwardcompany.FORWARDCOMPANY.ID);
		public static final UniqueKey<ImomessageRecord> KEY_IMOMESSAGE_PRIMARY = createUniqueKey(Imomessage.IMOMESSAGE, Imomessage.IMOMESSAGE.ID);
		public static final UniqueKey<LogisticsdataRecord> KEY_LOGISTICSDATA_PRIMARY = createUniqueKey(Logisticsdata.LOGISTICSDATA, Logisticsdata.LOGISTICSDATA.LOGISTICSDATAID);
		public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = createUniqueKey(Message.MESSAGE, Message.MESSAGE.MESSAGEID);
		public static final UniqueKey<NoteRecord> KEY_NOTE_PRIMARY = createUniqueKey(Note.NOTE, Note.NOTE.NOTEID);
		public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = createUniqueKey(Order.ORDER, Order.ORDER.ORDERID);
		public static final UniqueKey<PermissionRecord> KEY_PERMISSION_PRIMARY = createUniqueKey(Permission.PERMISSION, Permission.PERMISSION.PERMISSIONID);
		public static final UniqueKey<RelatedinfoRecord> KEY_RELATEDINFO_PRIMARY = createUniqueKey(Relatedinfo.RELATEDINFO, Relatedinfo.RELATEDINFO.RELATEDINFOID);
		public static final UniqueKey<RelationRecord> KEY_RELATION_PRIMARY = createUniqueKey(Relation.RELATION, Relation.RELATION.RELATIONID);
		public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = createUniqueKey(Role.ROLE, Role.ROLE.ROLEID);
		public static final UniqueKey<RolepermissionRecord> KEY_ROLEPERMISSION_PRIMARY = createUniqueKey(Rolepermission.ROLEPERMISSION, Rolepermission.ROLEPERMISSION.ROLEPERMISSIONID);
		public static final UniqueKey<ShopRecord> KEY_SHOP_PRIMARY = createUniqueKey(Shop.SHOP, Shop.SHOP.SHOPID);
		public static final UniqueKey<StaffRecord> KEY_STAFF_PRIMARY = createUniqueKey(Staff.STAFF, Staff.STAFF.STAFFID);
		public static final UniqueKey<StaffpermissionRecord> KEY_STAFFPERMISSION_PRIMARY = createUniqueKey(Staffpermission.STAFFPERMISSION, Staffpermission.STAFFPERMISSION.STAFFPERMISSIONID);
		public static final UniqueKey<SysexpresstemplateRecord> KEY_SYSEXPRESSTEMPLATE_PRIMARY = createUniqueKey(Sysexpresstemplate.SYSEXPRESSTEMPLATE, Sysexpresstemplate.SYSEXPRESSTEMPLATE.ID);
		public static final UniqueKey<TimeserverRecord> KEY_TIMESERVER_PRIMARY = createUniqueKey(Timeserver.TIMESERVER, Timeserver.TIMESERVER.TIMESERVERID);
		public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, User.USER.USERID);
	}
}
