/**
 * This class is generated by jOOQ
 */
package cn.kee.model;


import javax.annotation.Generated;

import cn.kee.model.tables.Addresslibrary;
import cn.kee.model.tables.Businesslibrary;
import cn.kee.model.tables.Center;
import cn.kee.model.tables.Client;
import cn.kee.model.tables.Coupon;
import cn.kee.model.tables.Databasechangelog;
import cn.kee.model.tables.Databasechangeloglock;
import cn.kee.model.tables.Evaluation;
import cn.kee.model.tables.Expresstemplate;
import cn.kee.model.tables.Forwardcompany;
import cn.kee.model.tables.Imomessage;
import cn.kee.model.tables.Logisticsdata;
import cn.kee.model.tables.Message;
import cn.kee.model.tables.Note;
import cn.kee.model.tables.Order;
import cn.kee.model.tables.Permission;
import cn.kee.model.tables.Relatedinfo;
import cn.kee.model.tables.Relation;
import cn.kee.model.tables.Role;
import cn.kee.model.tables.Rolepermission;
import cn.kee.model.tables.Shop;
import cn.kee.model.tables.Staff;
import cn.kee.model.tables.Staffpermission;
import cn.kee.model.tables.Sysexpresstemplate;
import cn.kee.model.tables.Timeserver;
import cn.kee.model.tables.User;


/**
 * Convenience access to all tables in ewp
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ewp.addresslibrary
	 */
	public static final Addresslibrary ADDRESSLIBRARY = cn.kee.model.tables.Addresslibrary.ADDRESSLIBRARY;

	/**
	 * The table ewp.businesslibrary
	 */
	public static final Businesslibrary BUSINESSLIBRARY = cn.kee.model.tables.Businesslibrary.BUSINESSLIBRARY;

	/**
	 * The table ewp.center
	 */
	public static final Center CENTER = cn.kee.model.tables.Center.CENTER;

	/**
	 * The table ewp.client
	 */
	public static final Client CLIENT = cn.kee.model.tables.Client.CLIENT;

	/**
	 * The table ewp.coupon
	 */
	public static final Coupon COUPON = cn.kee.model.tables.Coupon.COUPON;

	/**
	 * The table ewp.databasechangelog
	 */
	public static final Databasechangelog DATABASECHANGELOG = cn.kee.model.tables.Databasechangelog.DATABASECHANGELOG;

	/**
	 * The table ewp.databasechangeloglock
	 */
	public static final Databasechangeloglock DATABASECHANGELOGLOCK = cn.kee.model.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table ewp.evaluation
	 */
	public static final Evaluation EVALUATION = cn.kee.model.tables.Evaluation.EVALUATION;

	/**
	 * The table ewp.expresstemplate
	 */
	public static final Expresstemplate EXPRESSTEMPLATE = cn.kee.model.tables.Expresstemplate.EXPRESSTEMPLATE;

	/**
	 * The table ewp.forwardcompany
	 */
	public static final Forwardcompany FORWARDCOMPANY = cn.kee.model.tables.Forwardcompany.FORWARDCOMPANY;

	/**
	 * The table ewp.imomessage
	 */
	public static final Imomessage IMOMESSAGE = cn.kee.model.tables.Imomessage.IMOMESSAGE;

	/**
	 * The table ewp.logisticsdata
	 */
	public static final Logisticsdata LOGISTICSDATA = cn.kee.model.tables.Logisticsdata.LOGISTICSDATA;

	/**
	 * The table ewp.message
	 */
	public static final Message MESSAGE = cn.kee.model.tables.Message.MESSAGE;

	/**
	 * The table ewp.note
	 */
	public static final Note NOTE = cn.kee.model.tables.Note.NOTE;

	/**
	 * The table ewp.order
	 */
	public static final Order ORDER = cn.kee.model.tables.Order.ORDER;

	/**
	 * The table ewp.permission
	 */
	public static final Permission PERMISSION = cn.kee.model.tables.Permission.PERMISSION;

	/**
	 * The table ewp.relatedinfo
	 */
	public static final Relatedinfo RELATEDINFO = cn.kee.model.tables.Relatedinfo.RELATEDINFO;

	/**
	 * The table ewp.relation
	 */
	public static final Relation RELATION = cn.kee.model.tables.Relation.RELATION;

	/**
	 * The table ewp.role
	 */
	public static final Role ROLE = cn.kee.model.tables.Role.ROLE;

	/**
	 * The table ewp.rolepermission
	 */
	public static final Rolepermission ROLEPERMISSION = cn.kee.model.tables.Rolepermission.ROLEPERMISSION;

	/**
	 * The table ewp.shop
	 */
	public static final Shop SHOP = cn.kee.model.tables.Shop.SHOP;

	/**
	 * The table ewp.staff
	 */
	public static final Staff STAFF = cn.kee.model.tables.Staff.STAFF;

	/**
	 * The table ewp.staffpermission
	 */
	public static final Staffpermission STAFFPERMISSION = cn.kee.model.tables.Staffpermission.STAFFPERMISSION;

	/**
	 * The table ewp.sysexpresstemplate
	 */
	public static final Sysexpresstemplate SYSEXPRESSTEMPLATE = cn.kee.model.tables.Sysexpresstemplate.SYSEXPRESSTEMPLATE;

	/**
	 * The table ewp.timeserver
	 */
	public static final Timeserver TIMESERVER = cn.kee.model.tables.Timeserver.TIMESERVER;

	/**
	 * The table ewp.user
	 */
	public static final User USER = cn.kee.model.tables.User.USER;
}
