/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Center;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "center", schema = "ewp")
public class CenterRecord extends UpdatableRecordImpl<CenterRecord> implements Record20<String, Double, Double, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = -1397285217;

	/**
	 * Setter for <code>ewp.center.centerid</code>.
	 */
	public void setCenterid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.center.centerid</code>.
	 */
	@Id
	@Column(name = "centerid", unique = true, nullable = false, length = 32)
	public String getCenterid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.center.account</code>.
	 */
	public void setAccount(Double value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.center.account</code>.
	 */
	@Column(name = "account", precision = 12)
	public Double getAccount() {
		return (Double) getValue(1);
	}

	/**
	 * Setter for <code>ewp.center.coins</code>.
	 */
	public void setCoins(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.center.coins</code>.
	 */
	@Column(name = "coins", precision = 12)
	public Double getCoins() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>ewp.center.level</code>.
	 */
	public void setLevel(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.center.level</code>.
	 */
	@Column(name = "level", length = 32)
	public String getLevel() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.center.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.center.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.center.integral</code>.
	 */
	public void setIntegral(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.center.integral</code>.
	 */
	@Column(name = "integral", precision = 10)
	public Integer getIntegral() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ewp.center.etime</code>.
	 */
	public void setEtime(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.center.etime</code>.
	 */
	@Column(name = "etime", length = 32)
	public String getEtime() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.center.eattitude</code>.
	 */
	public void setEattitude(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.center.eattitude</code>.
	 */
	@Column(name = "eattitude", length = 32)
	public String getEattitude() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.center.percentage</code>.
	 */
	public void setPercentage(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.center.percentage</code>.
	 */
	@Column(name = "percentage", length = 32)
	public String getPercentage() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ewp.center.countone</code>.
	 */
	public void setCountone(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ewp.center.countone</code>.
	 */
	@Column(name = "countone", length = 32)
	public String getCountone() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>ewp.center.counttwo</code>.
	 */
	public void setCounttwo(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ewp.center.counttwo</code>.
	 */
	@Column(name = "counttwo", length = 32)
	public String getCounttwo() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>ewp.center.countthree</code>.
	 */
	public void setCountthree(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ewp.center.countthree</code>.
	 */
	@Column(name = "countthree", length = 32)
	public String getCountthree() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>ewp.center.countfour</code>.
	 */
	public void setCountfour(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ewp.center.countfour</code>.
	 */
	@Column(name = "countfour", length = 32)
	public String getCountfour() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>ewp.center.countfive</code>.
	 */
	public void setCountfive(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ewp.center.countfive</code>.
	 */
	@Column(name = "countfive", length = 32)
	public String getCountfive() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>ewp.center.apercentage</code>.
	 */
	public void setApercentage(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ewp.center.apercentage</code>.
	 */
	@Column(name = "apercentage", length = 32)
	public String getApercentage() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>ewp.center.acountone</code>.
	 */
	public void setAcountone(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ewp.center.acountone</code>.
	 */
	@Column(name = "acountone", length = 32)
	public String getAcountone() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>ewp.center.acounttwo</code>.
	 */
	public void setAcounttwo(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ewp.center.acounttwo</code>.
	 */
	@Column(name = "acounttwo", length = 32)
	public String getAcounttwo() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>ewp.center.acountthree</code>.
	 */
	public void setAcountthree(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ewp.center.acountthree</code>.
	 */
	@Column(name = "acountthree", length = 32)
	public String getAcountthree() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>ewp.center.acountfour</code>.
	 */
	public void setAcountfour(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ewp.center.acountfour</code>.
	 */
	@Column(name = "acountfour", length = 32)
	public String getAcountfour() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>ewp.center.acountfive</code>.
	 */
	public void setAcountfive(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>ewp.center.acountfive</code>.
	 */
	@Column(name = "acountfive", length = 32)
	public String getAcountfive() {
		return (String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row20<String, Double, Double, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
		return (Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row20<String, Double, Double, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
		return (Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Center.CENTER.CENTERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field2() {
		return Center.CENTER.ACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return Center.CENTER.COINS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Center.CENTER.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Center.CENTER.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Center.CENTER.INTEGRAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Center.CENTER.ETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Center.CENTER.EATTITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Center.CENTER.PERCENTAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Center.CENTER.COUNTONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Center.CENTER.COUNTTWO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Center.CENTER.COUNTTHREE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return Center.CENTER.COUNTFOUR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return Center.CENTER.COUNTFIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return Center.CENTER.APERCENTAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return Center.CENTER.ACOUNTONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field17() {
		return Center.CENTER.ACOUNTTWO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field18() {
		return Center.CENTER.ACOUNTTHREE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field19() {
		return Center.CENTER.ACOUNTFOUR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field20() {
		return Center.CENTER.ACOUNTFIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCenterid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value2() {
		return getAccount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getCoins();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIntegral();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getEtime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getEattitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getPercentage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getCountone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getCounttwo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getCountthree();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getCountfour();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getCountfive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getApercentage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getAcountone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value17() {
		return getAcounttwo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value18() {
		return getAcountthree();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value19() {
		return getAcountfour();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value20() {
		return getAcountfive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value1(String value) {
		setCenterid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value2(Double value) {
		setAccount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value3(Double value) {
		setCoins(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value4(String value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value5(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value6(Integer value) {
		setIntegral(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value7(String value) {
		setEtime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value8(String value) {
		setEattitude(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value9(String value) {
		setPercentage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value10(String value) {
		setCountone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value11(String value) {
		setCounttwo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value12(String value) {
		setCountthree(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value13(String value) {
		setCountfour(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value14(String value) {
		setCountfive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value15(String value) {
		setApercentage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value16(String value) {
		setAcountone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value17(String value) {
		setAcounttwo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value18(String value) {
		setAcountthree(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value19(String value) {
		setAcountfour(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord value20(String value) {
		setAcountfive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CenterRecord values(String value1, Double value2, Double value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		value20(value20);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CenterRecord
	 */
	public CenterRecord() {
		super(Center.CENTER);
	}

	/**
	 * Create a detached, initialised CenterRecord
	 */
	public CenterRecord(String centerid, Double account, Double coins, String level, String userid, Integer integral, String etime, String eattitude, String percentage, String countone, String counttwo, String countthree, String countfour, String countfive, String apercentage, String acountone, String acounttwo, String acountthree, String acountfour, String acountfive) {
		super(Center.CENTER);

		setValue(0, centerid);
		setValue(1, account);
		setValue(2, coins);
		setValue(3, level);
		setValue(4, userid);
		setValue(5, integral);
		setValue(6, etime);
		setValue(7, eattitude);
		setValue(8, percentage);
		setValue(9, countone);
		setValue(10, counttwo);
		setValue(11, countthree);
		setValue(12, countfour);
		setValue(13, countfive);
		setValue(14, apercentage);
		setValue(15, acountone);
		setValue(16, acounttwo);
		setValue(17, acountthree);
		setValue(18, acountfour);
		setValue(19, acountfive);
	}
}
