/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Coupon;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "coupon", schema = "ewp")
public class CouponRecord extends UpdatableRecordImpl<CouponRecord> implements Record6<String, String, String, Double, String, String> {

	private static final long serialVersionUID = 2085326606;

	/**
	 * Setter for <code>ewp.coupon.couponid</code>.
	 */
	public void setCouponid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.coupon.couponid</code>.
	 */
	@Id
	@Column(name = "couponid", unique = true, nullable = false, length = 32)
	public String getCouponid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.coupon.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.coupon.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.coupon.picture</code>.
	 */
	public void setPicture(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.coupon.picture</code>.
	 */
	@Column(name = "picture", length = 256)
	public String getPicture() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.coupon.momey</code>.
	 */
	public void setMomey(Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.coupon.momey</code>.
	 */
	@Column(name = "momey", precision = 12)
	public Double getMomey() {
		return (Double) getValue(3);
	}

	/**
	 * Setter for <code>ewp.coupon.context</code>.
	 */
	public void setContext(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.coupon.context</code>.
	 */
	@Column(name = "context", length = 256)
	public String getContext() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.coupon.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.coupon.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, Double, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, Double, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Coupon.COUPON.COUPONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Coupon.COUPON.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Coupon.COUPON.PICTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field4() {
		return Coupon.COUPON.MOMEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Coupon.COUPON.CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Coupon.COUPON.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCouponid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPicture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value4() {
		return getMomey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value1(String value) {
		setCouponid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value3(String value) {
		setPicture(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value4(Double value) {
		setMomey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value5(String value) {
		setContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value6(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord values(String value1, String value2, String value3, Double value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CouponRecord
	 */
	public CouponRecord() {
		super(Coupon.COUPON);
	}

	/**
	 * Create a detached, initialised CouponRecord
	 */
	public CouponRecord(String couponid, String name, String picture, Double momey, String context, String userid) {
		super(Coupon.COUPON);

		setValue(0, couponid);
		setValue(1, name);
		setValue(2, picture);
		setValue(3, momey);
		setValue(4, context);
		setValue(5, userid);
	}
}
