/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Databasechangelog;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "databasechangelog", schema = "ewp", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"ID", "AUTHOR", "FILENAME"})
})
public class DatabasechangelogRecord extends UpdatableRecordImpl<DatabasechangelogRecord> implements Record9<String, String, String, Timestamp, String, String, String, String, String> {

	private static final long serialVersionUID = -191468868;

	/**
	 * Setter for <code>ewp.databasechangelog.ID</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.ID</code>.
	 */
	@Column(name = "ID", nullable = false, length = 63)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.AUTHOR</code>.
	 */
	public void setAuthor(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.AUTHOR</code>.
	 */
	@Column(name = "AUTHOR", nullable = false, length = 63)
	public String getAuthor() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.FILENAME</code>.
	 */
	public void setFilename(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.FILENAME</code>.
	 */
	@Column(name = "FILENAME", nullable = false, length = 200)
	public String getFilename() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.DATEEXECUTED</code>.
	 */
	public void setDateexecuted(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.DATEEXECUTED</code>.
	 */
	@Column(name = "DATEEXECUTED", nullable = false)
	public Timestamp getDateexecuted() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.MD5SUM</code>.
	 */
	public void setMd5sum(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.MD5SUM</code>.
	 */
	@Column(name = "MD5SUM", length = 32)
	public String getMd5sum() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.DESCRIPTION</code>.
	 */
	public void setDescription(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.DESCRIPTION</code>.
	 */
	@Column(name = "DESCRIPTION", length = 255)
	public String getDescription() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.COMMENTS</code>.
	 */
	public void setComments(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.COMMENTS</code>.
	 */
	@Column(name = "COMMENTS", length = 255)
	public String getComments() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.TAG</code>.
	 */
	public void setTag(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.TAG</code>.
	 */
	@Column(name = "TAG", length = 255)
	public String getTag() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.databasechangelog.LIQUIBASE</code>.
	 */
	public void setLiquibase(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.databasechangelog.LIQUIBASE</code>.
	 */
	@Column(name = "LIQUIBASE", length = 10)
	public String getLiquibase() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, Timestamp, String, String, String, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, Timestamp, String, String, String, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Databasechangelog.DATABASECHANGELOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Databasechangelog.DATABASECHANGELOG.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Databasechangelog.DATABASECHANGELOG.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Databasechangelog.DATABASECHANGELOG.DATEEXECUTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Databasechangelog.DATABASECHANGELOG.MD5SUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Databasechangelog.DATABASECHANGELOG.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Databasechangelog.DATABASECHANGELOG.COMMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Databasechangelog.DATABASECHANGELOG.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Databasechangelog.DATABASECHANGELOG.LIQUIBASE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getDateexecuted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMd5sum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getComments();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getLiquibase();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value2(String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value3(String value) {
		setFilename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value4(Timestamp value) {
		setDateexecuted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value5(String value) {
		setMd5sum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value6(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value7(String value) {
		setComments(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value8(String value) {
		setTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord value9(String value) {
		setLiquibase(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatabasechangelogRecord values(String value1, String value2, String value3, Timestamp value4, String value5, String value6, String value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DatabasechangelogRecord
	 */
	public DatabasechangelogRecord() {
		super(Databasechangelog.DATABASECHANGELOG);
	}

	/**
	 * Create a detached, initialised DatabasechangelogRecord
	 */
	public DatabasechangelogRecord(String id, String author, String filename, Timestamp dateexecuted, String md5sum, String description, String comments, String tag, String liquibase) {
		super(Databasechangelog.DATABASECHANGELOG);

		setValue(0, id);
		setValue(1, author);
		setValue(2, filename);
		setValue(3, dateexecuted);
		setValue(4, md5sum);
		setValue(5, description);
		setValue(6, comments);
		setValue(7, tag);
		setValue(8, liquibase);
	}
}
