/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Forwardcompany;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "forwardcompany", schema = "ewp")
public class ForwardcompanyRecord extends UpdatableRecordImpl<ForwardcompanyRecord> implements Record11<String, String, Integer, String, String, Integer, String, String, String, String, String> {

	private static final long serialVersionUID = 1425305640;

	/**
	 * Setter for <code>ewp.forwardcompany.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.type</code>.
	 */
	public void setType(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.type</code>.
	 */
	@Column(name = "type", precision = 10)
	public Integer getType() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.memo</code>.
	 */
	public void setMemo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.memo</code>.
	 */
	@Column(name = "memo", length = 32)
	public String getMemo() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.code</code>.
	 */
	public void setCode(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.code</code>.
	 */
	@Column(name = "code", length = 32)
	public String getCode() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.sortno</code>.
	 */
	public void setSortno(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.sortno</code>.
	 */
	@Column(name = "sortno", precision = 10)
	public Integer getSortno() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.templateimgurl</code>.
	 */
	public void setTemplateimgurl(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.templateimgurl</code>.
	 */
	@Column(name = "templateimgurl", length = 255)
	public String getTemplateimgurl() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.pagewidth</code>.
	 */
	public void setPagewidth(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.pagewidth</code>.
	 */
	@Column(name = "pagewidth", length = 32)
	public String getPagewidth() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.pageheight</code>.
	 */
	public void setPageheight(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.pageheight</code>.
	 */
	@Column(name = "pageheight", length = 32)
	public String getPageheight() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.templatevalue</code>.
	 */
	public void setTemplatevalue(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.templatevalue</code>.
	 */
	@Column(name = "templatevalue", length = 5000)
	public String getTemplatevalue() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>ewp.forwardcompany.shortname</code>.
	 */
	public void setShortname(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ewp.forwardcompany.shortname</code>.
	 */
	@Column(name = "shortname", length = 32)
	public String getShortname() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, Integer, String, String, Integer, String, String, String, String, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, Integer, String, String, Integer, String, String, String, String, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Forwardcompany.FORWARDCOMPANY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Forwardcompany.FORWARDCOMPANY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Forwardcompany.FORWARDCOMPANY.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Forwardcompany.FORWARDCOMPANY.MEMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Forwardcompany.FORWARDCOMPANY.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Forwardcompany.FORWARDCOMPANY.SORTNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Forwardcompany.FORWARDCOMPANY.TEMPLATEIMGURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Forwardcompany.FORWARDCOMPANY.PAGEWIDTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Forwardcompany.FORWARDCOMPANY.PAGEHEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Forwardcompany.FORWARDCOMPANY.TEMPLATEVALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Forwardcompany.FORWARDCOMPANY.SHORTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMemo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getSortno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getTemplateimgurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getPagewidth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getPageheight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getTemplatevalue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getShortname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value3(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value4(String value) {
		setMemo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value5(String value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value6(Integer value) {
		setSortno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value7(String value) {
		setTemplateimgurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value8(String value) {
		setPagewidth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value9(String value) {
		setPageheight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value10(String value) {
		setTemplatevalue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord value11(String value) {
		setShortname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ForwardcompanyRecord values(String value1, String value2, Integer value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ForwardcompanyRecord
	 */
	public ForwardcompanyRecord() {
		super(Forwardcompany.FORWARDCOMPANY);
	}

	/**
	 * Create a detached, initialised ForwardcompanyRecord
	 */
	public ForwardcompanyRecord(String id, String name, Integer type, String memo, String code, Integer sortno, String templateimgurl, String pagewidth, String pageheight, String templatevalue, String shortname) {
		super(Forwardcompany.FORWARDCOMPANY);

		setValue(0, id);
		setValue(1, name);
		setValue(2, type);
		setValue(3, memo);
		setValue(4, code);
		setValue(5, sortno);
		setValue(6, templateimgurl);
		setValue(7, pagewidth);
		setValue(8, pageheight);
		setValue(9, templatevalue);
		setValue(10, shortname);
	}
}
