/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Message;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "message", schema = "ewp")
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record14<String, String, String, String, String, String, String, Integer, Timestamp, Integer, String, String, String, Integer> {

	private static final long serialVersionUID = -988749628;

	/**
	 * Setter for <code>ewp.message.messageid</code>.
	 */
	public void setMessageid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.message.messageid</code>.
	 */
	@Id
	@Column(name = "messageid", unique = true, nullable = false, length = 32)
	public String getMessageid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.message.type</code>.
	 */
	public void setType(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.message.type</code>.
	 */
	@Column(name = "type", length = 32)
	public String getType() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.message.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.message.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.message.staffid</code>.
	 */
	public void setStaffid(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.message.staffid</code>.
	 */
	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.message.context</code>.
	 */
	public void setContext(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.message.context</code>.
	 */
	@Column(name = "context", length = 256)
	public String getContext() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.message.orderid</code>.
	 */
	public void setOrderid(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.message.orderid</code>.
	 */
	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.message.sendtype</code>.
	 */
	public void setSendtype(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.message.sendtype</code>.
	 */
	@Column(name = "sendtype", length = 32)
	public String getSendtype() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.message.state</code>.
	 */
	public void setState(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.message.state</code>.
	 */
	@Column(name = "state", precision = 10)
	public Integer getState() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>ewp.message.time</code>.
	 */
	public void setTime(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.message.time</code>.
	 */
	@Column(name = "time")
	public Timestamp getTime() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>ewp.message.issms</code>.
	 */
	public void setIssms(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ewp.message.issms</code>.
	 */
	@Column(name = "issms", precision = 10)
	public Integer getIssms() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>ewp.message.mobile</code>.
	 */
	public void setMobile(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ewp.message.mobile</code>.
	 */
	@Column(name = "mobile", length = 64)
	public String getMobile() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>ewp.message.ostate</code>.
	 */
	public void setOstate(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ewp.message.ostate</code>.
	 */
	@Column(name = "ostate", length = 32)
	public String getOstate() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>ewp.message.targetid</code>.
	 */
	public void setTargetid(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ewp.message.targetid</code>.
	 */
	@Column(name = "targetid", length = 32)
	public String getTargetid() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>ewp.message.pushtype</code>.
	 */
	public void setPushtype(Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ewp.message.pushtype</code>.
	 */
	@Column(name = "pushtype", precision = 10)
	public Integer getPushtype() {
		return (Integer) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, String, Integer, Timestamp, Integer, String, String, String, Integer> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, String, Integer, Timestamp, Integer, String, String, String, Integer> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Message.MESSAGE.MESSAGEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Message.MESSAGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Message.MESSAGE.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Message.MESSAGE.STAFFID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Message.MESSAGE.CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Message.MESSAGE.ORDERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Message.MESSAGE.SENDTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Message.MESSAGE.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Message.MESSAGE.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Message.MESSAGE.ISSMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Message.MESSAGE.MOBILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Message.MESSAGE.OSTATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return Message.MESSAGE.TARGETID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field14() {
		return Message.MESSAGE.PUSHTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getMessageid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getStaffid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getOrderid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSendtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getIssms();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getOstate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getTargetid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value14() {
		return getPushtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value1(String value) {
		setMessageid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value2(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value3(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value4(String value) {
		setStaffid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value5(String value) {
		setContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value6(String value) {
		setOrderid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value7(String value) {
		setSendtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value8(Integer value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value9(Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value10(Integer value) {
		setIssms(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value11(String value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value12(String value) {
		setOstate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value13(String value) {
		setTargetid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value14(Integer value) {
		setPushtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, Timestamp value9, Integer value10, String value11, String value12, String value13, Integer value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessageRecord
	 */
	public MessageRecord() {
		super(Message.MESSAGE);
	}

	/**
	 * Create a detached, initialised MessageRecord
	 */
	public MessageRecord(String messageid, String type, String userid, String staffid, String context, String orderid, String sendtype, Integer state, Timestamp time, Integer issms, String mobile, String ostate, String targetid, Integer pushtype) {
		super(Message.MESSAGE);

		setValue(0, messageid);
		setValue(1, type);
		setValue(2, userid);
		setValue(3, staffid);
		setValue(4, context);
		setValue(5, orderid);
		setValue(6, sendtype);
		setValue(7, state);
		setValue(8, time);
		setValue(9, issms);
		setValue(10, mobile);
		setValue(11, ostate);
		setValue(12, targetid);
		setValue(13, pushtype);
	}
}
