/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Permission;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "permission", schema = "ewp")
public class PermissionRecord extends UpdatableRecordImpl<PermissionRecord> implements Record9<String, String, Integer, Integer, String, Integer, Integer, Integer, String> {

	private static final long serialVersionUID = -1120337490;

	/**
	 * Setter for <code>ewp.permission.permissionid</code>.
	 */
	public void setPermissionid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.permission.permissionid</code>.
	 */
	@Id
	@Column(name = "permissionid", unique = true, nullable = false, length = 32)
	public String getPermissionid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.permission.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.permission.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.permission.type</code>.
	 */
	public void setType(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.permission.type</code>.
	 */
	@Column(name = "type", precision = 10)
	public Integer getType() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ewp.permission.status</code>.
	 */
	public void setStatus(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.permission.status</code>.
	 */
	@Column(name = "status", precision = 10)
	public Integer getStatus() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>ewp.permission.parentid</code>.
	 */
	public void setParentid(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.permission.parentid</code>.
	 */
	@Column(name = "parentid", length = 32)
	public String getParentid() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.permission.ordernum</code>.
	 */
	public void setOrdernum(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.permission.ordernum</code>.
	 */
	@Column(name = "ordernum", precision = 10)
	public Integer getOrdernum() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ewp.permission.level</code>.
	 */
	public void setLevel(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.permission.level</code>.
	 */
	@Column(name = "level", precision = 10)
	public Integer getLevel() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>ewp.permission.orderby</code>.
	 */
	public void setOrderby(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.permission.orderby</code>.
	 */
	@Column(name = "orderby", precision = 10)
	public Integer getOrderby() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>ewp.permission.action</code>.
	 */
	public void setAction(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.permission.action</code>.
	 */
	@Column(name = "action", length = 1024)
	public String getAction() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, Integer, Integer, String, Integer, Integer, Integer, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, Integer, Integer, String, Integer, Integer, Integer, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Permission.PERMISSION.PERMISSIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Permission.PERMISSION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Permission.PERMISSION.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Permission.PERMISSION.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Permission.PERMISSION.PARENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Permission.PERMISSION.ORDERNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Permission.PERMISSION.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Permission.PERMISSION.ORDERBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Permission.PERMISSION.ACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPermissionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getParentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getOrdernum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getOrderby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getAction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value1(String value) {
		setPermissionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value3(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value4(Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value5(String value) {
		setParentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value6(Integer value) {
		setOrdernum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value7(Integer value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value8(Integer value) {
		setOrderby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord value9(String value) {
		setAction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionRecord values(String value1, String value2, Integer value3, Integer value4, String value5, Integer value6, Integer value7, Integer value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PermissionRecord
	 */
	public PermissionRecord() {
		super(Permission.PERMISSION);
	}

	/**
	 * Create a detached, initialised PermissionRecord
	 */
	public PermissionRecord(String permissionid, String name, Integer type, Integer status, String parentid, Integer ordernum, Integer level, Integer orderby, String action) {
		super(Permission.PERMISSION);

		setValue(0, permissionid);
		setValue(1, name);
		setValue(2, type);
		setValue(3, status);
		setValue(4, parentid);
		setValue(5, ordernum);
		setValue(6, level);
		setValue(7, orderby);
		setValue(8, action);
	}
}
