/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Relatedinfo;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "relatedinfo", schema = "ewp")
public class RelatedinfoRecord extends UpdatableRecordImpl<RelatedinfoRecord> implements Record8<String, String, String, String, String, String, String, Integer> {

	private static final long serialVersionUID = -1026938771;

	/**
	 * Setter for <code>ewp.relatedinfo.relatedinfoid</code>.
	 */
	public void setRelatedinfoid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.relatedinfoid</code>.
	 */
	@Id
	@Column(name = "relatedinfoid", unique = true, nullable = false, length = 32)
	public String getRelatedinfoid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.orderid</code>.
	 */
	public void setOrderid(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.orderid</code>.
	 */
	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.picture</code>.
	 */
	public void setPicture(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.picture</code>.
	 */
	@Column(name = "picture", length = 256)
	public String getPicture() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.staffid</code>.
	 */
	public void setStaffid(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.staffid</code>.
	 */
	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.memo</code>.
	 */
	public void setMemo(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.memo</code>.
	 */
	@Column(name = "memo", length = 256)
	public String getMemo() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.sound</code>.
	 */
	public void setSound(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.sound</code>.
	 */
	@Column(name = "sound", length = 256)
	public String getSound() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.relatedinfo.type</code>.
	 */
	public void setType(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.relatedinfo.type</code>.
	 */
	@Column(name = "type", precision = 10)
	public Integer getType() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, String, String, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, String, String, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Relatedinfo.RELATEDINFO.RELATEDINFOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Relatedinfo.RELATEDINFO.ORDERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Relatedinfo.RELATEDINFO.PICTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Relatedinfo.RELATEDINFO.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Relatedinfo.RELATEDINFO.STAFFID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Relatedinfo.RELATEDINFO.MEMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Relatedinfo.RELATEDINFO.SOUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Relatedinfo.RELATEDINFO.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getRelatedinfoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getOrderid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPicture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getStaffid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getMemo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSound();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value1(String value) {
		setRelatedinfoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value2(String value) {
		setOrderid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value3(String value) {
		setPicture(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value4(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value5(String value) {
		setStaffid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value6(String value) {
		setMemo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value7(String value) {
		setSound(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord value8(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedinfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RelatedinfoRecord
	 */
	public RelatedinfoRecord() {
		super(Relatedinfo.RELATEDINFO);
	}

	/**
	 * Create a detached, initialised RelatedinfoRecord
	 */
	public RelatedinfoRecord(String relatedinfoid, String orderid, String picture, String userid, String staffid, String memo, String sound, Integer type) {
		super(Relatedinfo.RELATEDINFO);

		setValue(0, relatedinfoid);
		setValue(1, orderid);
		setValue(2, picture);
		setValue(3, userid);
		setValue(4, staffid);
		setValue(5, memo);
		setValue(6, sound);
		setValue(7, type);
	}
}
