/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.Timeserver;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "timeserver", schema = "ewp")
public class TimeserverRecord extends UpdatableRecordImpl<TimeserverRecord> implements Record6<String, Double, Double, String, String, Integer> {

	private static final long serialVersionUID = 23890869;

	/**
	 * Setter for <code>ewp.timeserver.timeserverid</code>.
	 */
	public void setTimeserverid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.timeserver.timeserverid</code>.
	 */
	@Id
	@Column(name = "timeserverid", unique = true, nullable = false, length = 32)
	public String getTimeserverid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.timeserver.duration</code>.
	 */
	public void setDuration(Double value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.timeserver.duration</code>.
	 */
	@Column(name = "duration", precision = 12)
	public Double getDuration() {
		return (Double) getValue(1);
	}

	/**
	 * Setter for <code>ewp.timeserver.money</code>.
	 */
	public void setMoney(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.timeserver.money</code>.
	 */
	@Column(name = "money", precision = 12)
	public Double getMoney() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>ewp.timeserver.name</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.timeserver.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.timeserver.memo</code>.
	 */
	public void setMemo(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.timeserver.memo</code>.
	 */
	@Column(name = "memo", length = 256)
	public String getMemo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.timeserver.isdefault</code>.
	 */
	public void setIsdefault(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.timeserver.isdefault</code>.
	 */
	@Column(name = "isdefault", precision = 10)
	public Integer getIsdefault() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, Double, Double, String, String, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, Double, Double, String, String, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Timeserver.TIMESERVER.TIMESERVERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field2() {
		return Timeserver.TIMESERVER.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return Timeserver.TIMESERVER.MONEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Timeserver.TIMESERVER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Timeserver.TIMESERVER.MEMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Timeserver.TIMESERVER.ISDEFAULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getTimeserverid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value2() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getMoney();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMemo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIsdefault();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord value1(String value) {
		setTimeserverid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord value2(Double value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord value3(Double value) {
		setMoney(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord value5(String value) {
		setMemo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord value6(Integer value) {
		setIsdefault(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeserverRecord values(String value1, Double value2, Double value3, String value4, String value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimeserverRecord
	 */
	public TimeserverRecord() {
		super(Timeserver.TIMESERVER);
	}

	/**
	 * Create a detached, initialised TimeserverRecord
	 */
	public TimeserverRecord(String timeserverid, Double duration, Double money, String name, String memo, Integer isdefault) {
		super(Timeserver.TIMESERVER);

		setValue(0, timeserverid);
		setValue(1, duration);
		setValue(2, money);
		setValue(3, name);
		setValue(4, memo);
		setValue(5, isdefault);
	}
}
