/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.records;


import com.wfs.model.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user", schema = "ewp")
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record19<String, String, String, String, Integer, String, String, String, String, Timestamp, Integer, Integer, String, String, String, String, String, Integer, String> {

	private static final long serialVersionUID = 1890685780;

	/**
	 * Setter for <code>ewp.user.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.user.userid</code>.
	 */
	@Id
	@Column(name = "userid", unique = true, nullable = false, length = 32)
	public String getUserid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.user.username</code>.
	 */
	public void setUsername(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.user.username</code>.
	 */
	@Column(name = "username", length = 64)
	public String getUsername() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.user.password</code>.
	 */
	public void setPassword(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.user.password</code>.
	 */
	@Column(name = "password", length = 32)
	public String getPassword() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.user.nick</code>.
	 */
	public void setNick(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.user.nick</code>.
	 */
	@Column(name = "nick", length = 32)
	public String getNick() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.user.type</code>.
	 */
	public void setType(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.user.type</code>.
	 */
	@Column(name = "type", precision = 10)
	public Integer getType() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ewp.user.telphone</code>.
	 */
	public void setTelphone(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.user.telphone</code>.
	 */
	@Column(name = "telphone", length = 64)
	public String getTelphone() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.user.name</code>.
	 */
	public void setName(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.user.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.user.image</code>.
	 */
	public void setImage(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.user.image</code>.
	 */
	@Column(name = "image", length = 256)
	public String getImage() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.user.securitycode</code>.
	 */
	public void setSecuritycode(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.user.securitycode</code>.
	 */
	@Column(name = "securitycode", length = 32)
	public String getSecuritycode() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ewp.user.registertime</code>.
	 */
	public void setRegistertime(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ewp.user.registertime</code>.
	 */
	@Column(name = "registertime")
	public Timestamp getRegistertime() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>ewp.user.isidentified</code>.
	 */
	public void setIsidentified(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ewp.user.isidentified</code>.
	 */
	@Column(name = "isidentified", precision = 10)
	public Integer getIsidentified() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>ewp.user.age</code>.
	 */
	public void setAge(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ewp.user.age</code>.
	 */
	@Column(name = "age", precision = 10)
	public Integer getAge() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>ewp.user.sex</code>.
	 */
	public void setSex(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ewp.user.sex</code>.
	 */
	@Column(name = "sex", length = 32)
	public String getSex() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>ewp.user.temptel</code>.
	 */
	public void setTemptel(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ewp.user.temptel</code>.
	 */
	@Column(name = "temptel", length = 64)
	public String getTemptel() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>ewp.user.channelid</code>.
	 */
	public void setChannelid(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ewp.user.channelid</code>.
	 */
	@Column(name = "channelid", length = 64)
	public String getChannelid() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>ewp.user.stationcode</code>.
	 */
	public void setStationcode(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ewp.user.stationcode</code>.
	 */
	@Column(name = "stationcode", length = 64)
	public String getStationcode() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>ewp.user.staffcode</code>.
	 */
	public void setStaffcode(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ewp.user.staffcode</code>.
	 */
	@Column(name = "staffcode", length = 64)
	public String getStaffcode() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>ewp.user.dtype</code>.
	 */
	public void setDtype(Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ewp.user.dtype</code>.
	 */
	@Column(name = "dtype", precision = 10)
	public Integer getDtype() {
		return (Integer) getValue(17);
	}

	/**
	 * Setter for <code>ewp.user.dserial</code>.
	 */
	public void setDserial(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ewp.user.dserial</code>.
	 */
	@Column(name = "dserial", length = 128)
	public String getDserial() {
		return (String) getValue(18);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record19 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<String, String, String, String, Integer, String, String, String, String, Timestamp, Integer, Integer, String, String, String, String, String, Integer, String> fieldsRow() {
		return (Row19) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<String, String, String, String, Integer, String, String, String, String, Timestamp, Integer, Integer, String, String, String, String, String, Integer, String> valuesRow() {
		return (Row19) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return User.USER.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return User.USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return User.USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return User.USER.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return User.USER.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return User.USER.TELPHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return User.USER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return User.USER.IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return User.USER.SECURITYCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return User.USER.REGISTERTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return User.USER.ISIDENTIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return User.USER.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return User.USER.SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return User.USER.TEMPTEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return User.USER.CHANNELID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return User.USER.STATIONCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field17() {
		return User.USER.STAFFCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field18() {
		return User.USER.DTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field19() {
		return User.USER.DSERIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTelphone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSecuritycode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getRegistertime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getIsidentified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getTemptel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getChannelid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getStationcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value17() {
		return getStaffcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value18() {
		return getDtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value19() {
		return getDserial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(String value) {
		setTelphone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(String value) {
		setImage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value9(String value) {
		setSecuritycode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value10(Timestamp value) {
		setRegistertime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value11(Integer value) {
		setIsidentified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value12(Integer value) {
		setAge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value13(String value) {
		setSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value14(String value) {
		setTemptel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value15(String value) {
		setChannelid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value16(String value) {
		setStationcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value17(String value) {
		setStaffcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value18(Integer value) {
		setDtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value19(String value) {
		setDserial(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(String value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9, Timestamp value10, Integer value11, Integer value12, String value13, String value14, String value15, String value16, String value17, Integer value18, String value19) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(String userid, String username, String password, String nick, Integer type, String telphone, String name, String image, String securitycode, Timestamp registertime, Integer isidentified, Integer age, String sex, String temptel, String channelid, String stationcode, String staffcode, Integer dtype, String dserial) {
		super(User.USER);

		setValue(0, userid);
		setValue(1, username);
		setValue(2, password);
		setValue(3, nick);
		setValue(4, type);
		setValue(5, telphone);
		setValue(6, name);
		setValue(7, image);
		setValue(8, securitycode);
		setValue(9, registertime);
		setValue(10, isidentified);
		setValue(11, age);
		setValue(12, sex);
		setValue(13, temptel);
		setValue(14, channelid);
		setValue(15, stationcode);
		setValue(16, staffcode);
		setValue(17, dtype);
		setValue(18, dserial);
	}
}
