/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import cn.kee.model.tables.Addresslibrary;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "addresslibrary", schema = "ewp")
public class AddresslibraryRecord extends UpdatableRecordImpl<AddresslibraryRecord> implements Record11<String, String, String, String, String, String, Integer, String, String, Integer, Integer> {

	private static final long serialVersionUID = 1073503473;

	/**
	 * Setter for <code>ewp.addresslibrary.addresslibraryid</code>.
	 */
	public void setAddresslibraryid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.addresslibraryid</code>.
	 */
	@Id
	@Column(name = "addresslibraryid", unique = true, nullable = false, length = 32)
	public String getAddresslibraryid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.provincial</code>.
	 */
	public void setProvincial(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.provincial</code>.
	 */
	@Column(name = "provincial", length = 32)
	public String getProvincial() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.city</code>.
	 */
	public void setCity(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.city</code>.
	 */
	@Column(name = "city", length = 32)
	public String getCity() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.district</code>.
	 */
	public void setDistrict(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.district</code>.
	 */
	@Column(name = "district", length = 32)
	public String getDistrict() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.address</code>.
	 */
	public void setAddress(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.address</code>.
	 */
	@Column(name = "address", length = 256)
	public String getAddress() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.type</code>.
	 */
	public void setType(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.type</code>.
	 */
	@Column(name = "type", precision = 10)
	public Integer getType() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.name</code>.
	 */
	public void setName(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.tel</code>.
	 */
	public void setTel(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.tel</code>.
	 */
	@Column(name = "tel", length = 64)
	public String getTel() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.isdel</code>.
	 */
	public void setIsdel(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.isdel</code>.
	 */
	@Column(name = "isdel", precision = 10)
	public Integer getIsdel() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>ewp.addresslibrary.isdefault</code>.
	 */
	public void setIsdefault(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ewp.addresslibrary.isdefault</code>.
	 */
	@Column(name = "isdefault", precision = 10)
	public Integer getIsdefault() {
		return (Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, String, String, Integer, String, String, Integer, Integer> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, String, String, Integer, String, String, Integer, Integer> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Addresslibrary.ADDRESSLIBRARY.ADDRESSLIBRARYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Addresslibrary.ADDRESSLIBRARY.PROVINCIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Addresslibrary.ADDRESSLIBRARY.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Addresslibrary.ADDRESSLIBRARY.DISTRICT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Addresslibrary.ADDRESSLIBRARY.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Addresslibrary.ADDRESSLIBRARY.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Addresslibrary.ADDRESSLIBRARY.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Addresslibrary.ADDRESSLIBRARY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Addresslibrary.ADDRESSLIBRARY.TEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Addresslibrary.ADDRESSLIBRARY.ISDEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return Addresslibrary.ADDRESSLIBRARY.ISDEFAULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAddresslibraryid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getProvincial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDistrict();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getTel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getIsdel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getIsdefault();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value1(String value) {
		setAddresslibraryid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value2(String value) {
		setProvincial(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value3(String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value4(String value) {
		setDistrict(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value5(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value6(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value7(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value8(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value9(String value) {
		setTel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value10(Integer value) {
		setIsdel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord value11(Integer value) {
		setIsdefault(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddresslibraryRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8, String value9, Integer value10, Integer value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AddresslibraryRecord
	 */
	public AddresslibraryRecord() {
		super(Addresslibrary.ADDRESSLIBRARY);
	}

	/**
	 * Create a detached, initialised AddresslibraryRecord
	 */
	public AddresslibraryRecord(String addresslibraryid, String provincial, String city, String district, String address, String userid, Integer type, String name, String tel, Integer isdel, Integer isdefault) {
		super(Addresslibrary.ADDRESSLIBRARY);

		setValue(0, addresslibraryid);
		setValue(1, provincial);
		setValue(2, city);
		setValue(3, district);
		setValue(4, address);
		setValue(5, userid);
		setValue(6, type);
		setValue(7, name);
		setValue(8, tel);
		setValue(9, isdel);
		setValue(10, isdefault);
	}
}
