/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import cn.kee.model.tables.Imomessage;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "imomessage", schema = "ewp")
public class ImomessageRecord extends UpdatableRecordImpl<ImomessageRecord> implements Record9<String, String, String, String, String, String, Timestamp, Integer, String> {

	private static final long serialVersionUID = 937174628;

	/**
	 * Setter for <code>ewp.imomessage.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.imomessage.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.imomessage.image</code>.
	 */
	public void setImage(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.image</code>.
	 */
	@Column(name = "image", length = 256)
	public String getImage() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.imomessage.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.imomessage.orderid</code>.
	 */
	public void setOrderid(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.orderid</code>.
	 */
	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.imomessage.evatype</code>.
	 */
	public void setEvatype(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.evatype</code>.
	 */
	@Column(name = "evatype", length = 32)
	public String getEvatype() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.imomessage.createtime</code>.
	 */
	public void setCreatetime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.createtime</code>.
	 */
	@Column(name = "createtime")
	public Timestamp getCreatetime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>ewp.imomessage.type</code>.
	 */
	public void setType(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.type</code>.
	 */
	@Column(name = "type", precision = 10)
	public Integer getType() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>ewp.imomessage.text</code>.
	 */
	public void setText(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.imomessage.text</code>.
	 */
	@Column(name = "text", length = 255)
	public String getText() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, String, Timestamp, Integer, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, String, Timestamp, Integer, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Imomessage.IMOMESSAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Imomessage.IMOMESSAGE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Imomessage.IMOMESSAGE.IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Imomessage.IMOMESSAGE.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Imomessage.IMOMESSAGE.ORDERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Imomessage.IMOMESSAGE.EVATYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Imomessage.IMOMESSAGE.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Imomessage.IMOMESSAGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Imomessage.IMOMESSAGE.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getOrderid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getEvatype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value3(String value) {
		setImage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value4(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value5(String value) {
		setOrderid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value6(String value) {
		setEvatype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value7(Timestamp value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value8(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord value9(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImomessageRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, Integer value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ImomessageRecord
	 */
	public ImomessageRecord() {
		super(Imomessage.IMOMESSAGE);
	}

	/**
	 * Create a detached, initialised ImomessageRecord
	 */
	public ImomessageRecord(String id, String name, String image, String userid, String orderid, String evatype, Timestamp createtime, Integer type, String text) {
		super(Imomessage.IMOMESSAGE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, image);
		setValue(3, userid);
		setValue(4, orderid);
		setValue(5, evatype);
		setValue(6, createtime);
		setValue(7, type);
		setValue(8, text);
	}
}
