/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import cn.kee.model.tables.Relation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "relation", schema = "ewp")
public class RelationRecord extends UpdatableRecordImpl<RelationRecord> implements Record9<String, String, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = -585062961;

	/**
	 * Setter for <code>ewp.relation.relationid</code>.
	 */
	public void setRelationid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.relation.relationid</code>.
	 */
	@Id
	@Column(name = "relationid", unique = true, nullable = false, length = 32)
	public String getRelationid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.relation.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.relation.userid</code>.
	 */
	@Column(name = "userid", length = 32)
	public String getUserid() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.relation.staffid</code>.
	 */
	public void setStaffid(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.relation.staffid</code>.
	 */
	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.relation.memo</code>.
	 */
	public void setMemo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.relation.memo</code>.
	 */
	@Column(name = "memo", length = 256)
	public String getMemo() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.relation.followtype</code>.
	 */
	public void setFollowtype(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.relation.followtype</code>.
	 */
	@Column(name = "followtype", length = 64)
	public String getFollowtype() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.relation.uname</code>.
	 */
	public void setUname(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.relation.uname</code>.
	 */
	@Column(name = "uname", length = 32)
	public String getUname() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ewp.relation.telphone</code>.
	 */
	public void setTelphone(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.relation.telphone</code>.
	 */
	@Column(name = "telphone", length = 32)
	public String getTelphone() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.relation.address</code>.
	 */
	public void setAddress(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.relation.address</code>.
	 */
	@Column(name = "address", length = 1024)
	public String getAddress() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.relation.landline</code>.
	 */
	public void setLandline(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.relation.landline</code>.
	 */
	@Column(name = "landline", length = 64)
	public String getLandline() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, String, String, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, String, String, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Relation.RELATION.RELATIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Relation.RELATION.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Relation.RELATION.STAFFID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Relation.RELATION.MEMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Relation.RELATION.FOLLOWTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Relation.RELATION.UNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Relation.RELATION.TELPHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Relation.RELATION.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Relation.RELATION.LANDLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getRelationid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getStaffid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMemo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getFollowtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getUname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getTelphone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getLandline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value1(String value) {
		setRelationid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value2(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value3(String value) {
		setStaffid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value4(String value) {
		setMemo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value5(String value) {
		setFollowtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value6(String value) {
		setUname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value7(String value) {
		setTelphone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value8(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord value9(String value) {
		setLandline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RelationRecord
	 */
	public RelationRecord() {
		super(Relation.RELATION);
	}

	/**
	 * Create a detached, initialised RelationRecord
	 */
	public RelationRecord(String relationid, String userid, String staffid, String memo, String followtype, String uname, String telphone, String address, String landline) {
		super(Relation.RELATION);

		setValue(0, relationid);
		setValue(1, userid);
		setValue(2, staffid);
		setValue(3, memo);
		setValue(4, followtype);
		setValue(5, uname);
		setValue(6, telphone);
		setValue(7, address);
		setValue(8, landline);
	}
}
