/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import cn.kee.model.tables.Sysexpresstemplate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sysexpresstemplate", schema = "ewp")
public class SysexpresstemplateRecord extends UpdatableRecordImpl<SysexpresstemplateRecord> implements Record10<String, String, String, String, String, Integer, String, String, String, Integer> {

	private static final long serialVersionUID = 1118465263;

	/**
	 * Setter for <code>ewp.sysexpresstemplate.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.name</code>.
	 */
	@Column(name = "name", length = 32)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.image</code>.
	 */
	public void setImage(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.image</code>.
	 */
	@Column(name = "image", length = 256)
	public String getImage() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.clientid</code>.
	 */
	public void setClientid(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.clientid</code>.
	 */
	@Column(name = "clientid", length = 32)
	public String getClientid() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.forwardcompanyid</code>.
	 */
	public void setForwardcompanyid(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.forwardcompanyid</code>.
	 */
	@Column(name = "forwardcompanyid", length = 32)
	public String getForwardcompanyid() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.isdefault</code>.
	 */
	public void setIsdefault(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.isdefault</code>.
	 */
	@Column(name = "isdefault", precision = 10)
	public Integer getIsdefault() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.width</code>.
	 */
	public void setWidth(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.width</code>.
	 */
	@Column(name = "width", length = 32)
	public String getWidth() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.height</code>.
	 */
	public void setHeight(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.height</code>.
	 */
	@Column(name = "height", length = 32)
	public String getHeight() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.value</code>.
	 */
	public void setValue(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.value</code>.
	 */
	@Column(name = "value", length = 5000)
	public String getValue() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ewp.sysexpresstemplate.needsendcode</code>.
	 */
	public void setNeedsendcode(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ewp.sysexpresstemplate.needsendcode</code>.
	 */
	@Column(name = "needsendcode", precision = 10)
	public Integer getNeedsendcode() {
		return (Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, String, String, String, String, Integer, String, String, String, Integer> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, String, String, String, String, Integer, String, String, String, Integer> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.CLIENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.FORWARDCOMPANYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.ISDEFAULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.WIDTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.HEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Sysexpresstemplate.SYSEXPRESSTEMPLATE.NEEDSENDCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getClientid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getForwardcompanyid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIsdefault();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getWidth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getHeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getNeedsendcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value3(String value) {
		setImage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value4(String value) {
		setClientid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value5(String value) {
		setForwardcompanyid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value6(Integer value) {
		setIsdefault(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value7(String value) {
		setWidth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value8(String value) {
		setHeight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value9(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord value10(Integer value) {
		setNeedsendcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysexpresstemplateRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, Integer value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SysexpresstemplateRecord
	 */
	public SysexpresstemplateRecord() {
		super(Sysexpresstemplate.SYSEXPRESSTEMPLATE);
	}

	/**
	 * Create a detached, initialised SysexpresstemplateRecord
	 */
	public SysexpresstemplateRecord(String id, String name, String image, String clientid, String forwardcompanyid, Integer isdefault, String width, String height, String value, Integer needsendcode) {
		super(Sysexpresstemplate.SYSEXPRESSTEMPLATE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, image);
		setValue(3, clientid);
		setValue(4, forwardcompanyid);
		setValue(5, isdefault);
		setValue(6, width);
		setValue(7, height);
		setValue(8, value);
		setValue(9, needsendcode);
	}
}
