/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "addresslibrary", schema = "ewp")
public class Addresslibrary implements Serializable {

	private static final long serialVersionUID = 448154028;

	private String  addresslibraryid;
	private String  provincial;
	private String  city;
	private String  district;
	private String  address;
	private String  userid;
	private Integer type;
	private String  name;
	private String  tel;
	private Integer isdel;
	private Integer isdefault;

	public Addresslibrary() {}

	public Addresslibrary(Addresslibrary value) {
		this.addresslibraryid = value.addresslibraryid;
		this.provincial = value.provincial;
		this.city = value.city;
		this.district = value.district;
		this.address = value.address;
		this.userid = value.userid;
		this.type = value.type;
		this.name = value.name;
		this.tel = value.tel;
		this.isdel = value.isdel;
		this.isdefault = value.isdefault;
	}

	public Addresslibrary(
		String  addresslibraryid,
		String  provincial,
		String  city,
		String  district,
		String  address,
		String  userid,
		Integer type,
		String  name,
		String  tel,
		Integer isdel,
		Integer isdefault
	) {
		this.addresslibraryid = addresslibraryid;
		this.provincial = provincial;
		this.city = city;
		this.district = district;
		this.address = address;
		this.userid = userid;
		this.type = type;
		this.name = name;
		this.tel = tel;
		this.isdel = isdel;
		this.isdefault = isdefault;
	}

	@Id
	@Column(name = "addresslibraryid", unique = true, nullable = false, length = 32)
	public String getAddresslibraryid() {
		return this.addresslibraryid;
	}

	public void setAddresslibraryid(String addresslibraryid) {
		this.addresslibraryid = addresslibraryid;
	}

	@Column(name = "provincial", length = 32)
	public String getProvincial() {
		return this.provincial;
	}

	public void setProvincial(String provincial) {
		this.provincial = provincial;
	}

	@Column(name = "city", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "district", length = 32)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tel", length = 64)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "isdel", precision = 10)
	public Integer getIsdel() {
		return this.isdel;
	}

	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	@Column(name = "isdefault", precision = 10)
	public Integer getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Integer isdefault) {
		this.isdefault = isdefault;
	}
}
