/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "businesslibrary", schema = "ewp")
public class Businesslibrary implements Serializable {

	private static final long serialVersionUID = -1980823657;

	private String    businesslibraryid;
	private String    orderid;
	private String    action;
	private Timestamp createtime;
	private String    userid;
	private String    staffid;
	private String    memo;
	private String    code;

	public Businesslibrary() {}

	public Businesslibrary(Businesslibrary value) {
		this.businesslibraryid = value.businesslibraryid;
		this.orderid = value.orderid;
		this.action = value.action;
		this.createtime = value.createtime;
		this.userid = value.userid;
		this.staffid = value.staffid;
		this.memo = value.memo;
		this.code = value.code;
	}

	public Businesslibrary(
		String    businesslibraryid,
		String    orderid,
		String    action,
		Timestamp createtime,
		String    userid,
		String    staffid,
		String    memo,
		String    code
	) {
		this.businesslibraryid = businesslibraryid;
		this.orderid = orderid;
		this.action = action;
		this.createtime = createtime;
		this.userid = userid;
		this.staffid = staffid;
		this.memo = memo;
		this.code = code;
	}

	@Id
	@Column(name = "businesslibraryid", unique = true, nullable = false, length = 32)
	public String getBusinesslibraryid() {
		return this.businesslibraryid;
	}

	public void setBusinesslibraryid(String businesslibraryid) {
		this.businesslibraryid = businesslibraryid;
	}

	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "action", length = 512)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "createtime")
	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return this.staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	@Column(name = "memo", length = 256)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "code", length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
}
