/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "client", schema = "ewp")
public class Client implements Serializable {

	private static final long serialVersionUID = -664366155;

	private String  clientid;
	private String  name;
	private Integer type;
	private String  address;
	private String  phone;
	private Integer status;
	private String  memo;

	public Client() {}

	public Client(Client value) {
		this.clientid = value.clientid;
		this.name = value.name;
		this.type = value.type;
		this.address = value.address;
		this.phone = value.phone;
		this.status = value.status;
		this.memo = value.memo;
	}

	public Client(
		String  clientid,
		String  name,
		Integer type,
		String  address,
		String  phone,
		Integer status,
		String  memo
	) {
		this.clientid = clientid;
		this.name = name;
		this.type = type;
		this.address = address;
		this.phone = phone;
		this.status = status;
		this.memo = memo;
	}

	@Id
	@Column(name = "clientid", unique = true, nullable = false, length = 32)
	public String getClientid() {
		return this.clientid;
	}

	public void setClientid(String clientid) {
		this.clientid = clientid;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "address", length = 32)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 32)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "status", precision = 10)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "memo", length = 64)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}
}
