/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "coupon", schema = "ewp")
public class Coupon implements Serializable {

	private static final long serialVersionUID = -1833226940;

	private String couponid;
	private String name;
	private String picture;
	private Double momey;
	private String context;
	private String userid;

	public Coupon() {}

	public Coupon(Coupon value) {
		this.couponid = value.couponid;
		this.name = value.name;
		this.picture = value.picture;
		this.momey = value.momey;
		this.context = value.context;
		this.userid = value.userid;
	}

	public Coupon(
		String couponid,
		String name,
		String picture,
		Double momey,
		String context,
		String userid
	) {
		this.couponid = couponid;
		this.name = name;
		this.picture = picture;
		this.momey = momey;
		this.context = context;
		this.userid = userid;
	}

	@Id
	@Column(name = "couponid", unique = true, nullable = false, length = 32)
	public String getCouponid() {
		return this.couponid;
	}

	public void setCouponid(String couponid) {
		this.couponid = couponid;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture", length = 256)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "momey", precision = 12)
	public Double getMomey() {
		return this.momey;
	}

	public void setMomey(Double momey) {
		this.momey = momey;
	}

	@Column(name = "context", length = 256)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
}
