/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "expresstemplate", schema = "ewp")
public class Expresstemplate implements Serializable {

	private static final long serialVersionUID = 296564584;

	private String  id;
	private String  name;
	private String  initastr;
	private String  clientid;
	private String  forwardcompanyid;
	private Integer isdefault;
	private String  pagewidth;
	private String  pageheight;
	private String  templatevalue;
	private Integer needsendcode;
	private Integer isopen;
	private String  templateimgurl;
	private String  printer;

	public Expresstemplate() {}

	public Expresstemplate(Expresstemplate value) {
		this.id = value.id;
		this.name = value.name;
		this.initastr = value.initastr;
		this.clientid = value.clientid;
		this.forwardcompanyid = value.forwardcompanyid;
		this.isdefault = value.isdefault;
		this.pagewidth = value.pagewidth;
		this.pageheight = value.pageheight;
		this.templatevalue = value.templatevalue;
		this.needsendcode = value.needsendcode;
		this.isopen = value.isopen;
		this.templateimgurl = value.templateimgurl;
		this.printer = value.printer;
	}

	public Expresstemplate(
		String  id,
		String  name,
		String  initastr,
		String  clientid,
		String  forwardcompanyid,
		Integer isdefault,
		String  pagewidth,
		String  pageheight,
		String  templatevalue,
		Integer needsendcode,
		Integer isopen,
		String  templateimgurl,
		String  printer
	) {
		this.id = id;
		this.name = name;
		this.initastr = initastr;
		this.clientid = clientid;
		this.forwardcompanyid = forwardcompanyid;
		this.isdefault = isdefault;
		this.pagewidth = pagewidth;
		this.pageheight = pageheight;
		this.templatevalue = templatevalue;
		this.needsendcode = needsendcode;
		this.isopen = isopen;
		this.templateimgurl = templateimgurl;
		this.printer = printer;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "initastr", length = 256)
	public String getInitastr() {
		return this.initastr;
	}

	public void setInitastr(String initastr) {
		this.initastr = initastr;
	}

	@Column(name = "clientid", length = 32)
	public String getClientid() {
		return this.clientid;
	}

	public void setClientid(String clientid) {
		this.clientid = clientid;
	}

	@Column(name = "forwardcompanyid", length = 32)
	public String getForwardcompanyid() {
		return this.forwardcompanyid;
	}

	public void setForwardcompanyid(String forwardcompanyid) {
		this.forwardcompanyid = forwardcompanyid;
	}

	@Column(name = "isdefault", precision = 10)
	public Integer getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Integer isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "pagewidth", length = 32)
	public String getPagewidth() {
		return this.pagewidth;
	}

	public void setPagewidth(String pagewidth) {
		this.pagewidth = pagewidth;
	}

	@Column(name = "pageheight", length = 32)
	public String getPageheight() {
		return this.pageheight;
	}

	public void setPageheight(String pageheight) {
		this.pageheight = pageheight;
	}

	@Column(name = "templatevalue", length = 5000)
	public String getTemplatevalue() {
		return this.templatevalue;
	}

	public void setTemplatevalue(String templatevalue) {
		this.templatevalue = templatevalue;
	}

	@Column(name = "needsendcode", precision = 10)
	public Integer getNeedsendcode() {
		return this.needsendcode;
	}

	public void setNeedsendcode(Integer needsendcode) {
		this.needsendcode = needsendcode;
	}

	@Column(name = "isopen", precision = 10)
	public Integer getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Integer isopen) {
		this.isopen = isopen;
	}

	@Column(name = "templateImgUrl", length = 255)
	public String getTemplateimgurl() {
		return this.templateimgurl;
	}

	public void setTemplateimgurl(String templateimgurl) {
		this.templateimgurl = templateimgurl;
	}

	@Column(name = "printer", length = 255)
	public String getPrinter() {
		return this.printer;
	}

	public void setPrinter(String printer) {
		this.printer = printer;
	}
}
