/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "imomessage", schema = "ewp")
public class Imomessage implements Serializable {

	private static final long serialVersionUID = 124807132;

	private String    id;
	private String    name;
	private String    image;
	private String    userid;
	private String    orderid;
	private String    evatype;
	private Timestamp createtime;
	private Integer   type;
	private String    text;

	public Imomessage() {}

	public Imomessage(Imomessage value) {
		this.id = value.id;
		this.name = value.name;
		this.image = value.image;
		this.userid = value.userid;
		this.orderid = value.orderid;
		this.evatype = value.evatype;
		this.createtime = value.createtime;
		this.type = value.type;
		this.text = value.text;
	}

	public Imomessage(
		String    id,
		String    name,
		String    image,
		String    userid,
		String    orderid,
		String    evatype,
		Timestamp createtime,
		Integer   type,
		String    text
	) {
		this.id = id;
		this.name = name;
		this.image = image;
		this.userid = userid;
		this.orderid = orderid;
		this.evatype = evatype;
		this.createtime = createtime;
		this.type = type;
		this.text = text;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", length = 256)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "evatype", length = 32)
	public String getEvatype() {
		return this.evatype;
	}

	public void setEvatype(String evatype) {
		this.evatype = evatype;
	}

	@Column(name = "createtime")
	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "text", length = 255)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}
}
