/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "order", schema = "ewp")
public class Order implements Serializable {

	private static final long serialVersionUID = -76794100;

	private String    orderid;
	private String    consignee;
	private String    telphone;
	private String    address;
	private String    receiveprovince;
	private String    receivecity;
	private String    receivedistrict;
	private String    sender;
	private String    stel;
	private String    senderaddress;
	private String    senderprovince;
	private String    sendercity;
	private String    senderdistrict;
	private String    signedway;
	private String    staffname;
	private String    stafftel;
	private String    sendcode;
	private Timestamp createtime;
	private String    userid;
	private String    staffid;
	private Double    totalprice;
	private Double    expresscharge;
	private Double    serverfee;
	private Double    discountfee;
	private String    payway;
	private Double    payfee;
	private String    serialnum;
	private String    sendstaffname;
	private String    sendstafftel;
	private String    sigedname;
	private String    sigedtel;
	private Integer   packagetype;
	private Double    weight;
	private String    detailname;
	private String    takeaddress;
	private String    reserveinfo;
	private Integer   iscancelsend;
	private Integer   isinsured;
	private String    state;
	private String    weightinfo;
	private String    dstaffid;
	private String    suserid;
	private Timestamp asbegin;
	private Timestamp apend;
	private Timestamp rdtime;
	private Integer   dcount;

	public Order() {}

	public Order(Order value) {
		this.orderid = value.orderid;
		this.consignee = value.consignee;
		this.telphone = value.telphone;
		this.address = value.address;
		this.receiveprovince = value.receiveprovince;
		this.receivecity = value.receivecity;
		this.receivedistrict = value.receivedistrict;
		this.sender = value.sender;
		this.stel = value.stel;
		this.senderaddress = value.senderaddress;
		this.senderprovince = value.senderprovince;
		this.sendercity = value.sendercity;
		this.senderdistrict = value.senderdistrict;
		this.signedway = value.signedway;
		this.staffname = value.staffname;
		this.stafftel = value.stafftel;
		this.sendcode = value.sendcode;
		this.createtime = value.createtime;
		this.userid = value.userid;
		this.staffid = value.staffid;
		this.totalprice = value.totalprice;
		this.expresscharge = value.expresscharge;
		this.serverfee = value.serverfee;
		this.discountfee = value.discountfee;
		this.payway = value.payway;
		this.payfee = value.payfee;
		this.serialnum = value.serialnum;
		this.sendstaffname = value.sendstaffname;
		this.sendstafftel = value.sendstafftel;
		this.sigedname = value.sigedname;
		this.sigedtel = value.sigedtel;
		this.packagetype = value.packagetype;
		this.weight = value.weight;
		this.detailname = value.detailname;
		this.takeaddress = value.takeaddress;
		this.reserveinfo = value.reserveinfo;
		this.iscancelsend = value.iscancelsend;
		this.isinsured = value.isinsured;
		this.state = value.state;
		this.weightinfo = value.weightinfo;
		this.dstaffid = value.dstaffid;
		this.suserid = value.suserid;
		this.asbegin = value.asbegin;
		this.apend = value.apend;
		this.rdtime = value.rdtime;
		this.dcount = value.dcount;
	}

	public Order(
		String    orderid,
		String    consignee,
		String    telphone,
		String    address,
		String    receiveprovince,
		String    receivecity,
		String    receivedistrict,
		String    sender,
		String    stel,
		String    senderaddress,
		String    senderprovince,
		String    sendercity,
		String    senderdistrict,
		String    signedway,
		String    staffname,
		String    stafftel,
		String    sendcode,
		Timestamp createtime,
		String    userid,
		String    staffid,
		Double    totalprice,
		Double    expresscharge,
		Double    serverfee,
		Double    discountfee,
		String    payway,
		Double    payfee,
		String    serialnum,
		String    sendstaffname,
		String    sendstafftel,
		String    sigedname,
		String    sigedtel,
		Integer   packagetype,
		Double    weight,
		String    detailname,
		String    takeaddress,
		String    reserveinfo,
		Integer   iscancelsend,
		Integer   isinsured,
		String    state,
		String    weightinfo,
		String    dstaffid,
		String    suserid,
		Timestamp asbegin,
		Timestamp apend,
		Timestamp rdtime,
		Integer   dcount
	) {
		this.orderid = orderid;
		this.consignee = consignee;
		this.telphone = telphone;
		this.address = address;
		this.receiveprovince = receiveprovince;
		this.receivecity = receivecity;
		this.receivedistrict = receivedistrict;
		this.sender = sender;
		this.stel = stel;
		this.senderaddress = senderaddress;
		this.senderprovince = senderprovince;
		this.sendercity = sendercity;
		this.senderdistrict = senderdistrict;
		this.signedway = signedway;
		this.staffname = staffname;
		this.stafftel = stafftel;
		this.sendcode = sendcode;
		this.createtime = createtime;
		this.userid = userid;
		this.staffid = staffid;
		this.totalprice = totalprice;
		this.expresscharge = expresscharge;
		this.serverfee = serverfee;
		this.discountfee = discountfee;
		this.payway = payway;
		this.payfee = payfee;
		this.serialnum = serialnum;
		this.sendstaffname = sendstaffname;
		this.sendstafftel = sendstafftel;
		this.sigedname = sigedname;
		this.sigedtel = sigedtel;
		this.packagetype = packagetype;
		this.weight = weight;
		this.detailname = detailname;
		this.takeaddress = takeaddress;
		this.reserveinfo = reserveinfo;
		this.iscancelsend = iscancelsend;
		this.isinsured = isinsured;
		this.state = state;
		this.weightinfo = weightinfo;
		this.dstaffid = dstaffid;
		this.suserid = suserid;
		this.asbegin = asbegin;
		this.apend = apend;
		this.rdtime = rdtime;
		this.dcount = dcount;
	}

	@Id
	@Column(name = "orderid", unique = true, nullable = false, length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "consignee", length = 256)
	public String getConsignee() {
		return this.consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	@Column(name = "telphone", length = 64)
	public String getTelphone() {
		return this.telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "receiveprovince", length = 32)
	public String getReceiveprovince() {
		return this.receiveprovince;
	}

	public void setReceiveprovince(String receiveprovince) {
		this.receiveprovince = receiveprovince;
	}

	@Column(name = "receivecity", length = 32)
	public String getReceivecity() {
		return this.receivecity;
	}

	public void setReceivecity(String receivecity) {
		this.receivecity = receivecity;
	}

	@Column(name = "receivedistrict", length = 32)
	public String getReceivedistrict() {
		return this.receivedistrict;
	}

	public void setReceivedistrict(String receivedistrict) {
		this.receivedistrict = receivedistrict;
	}

	@Column(name = "sender", length = 256)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "stel", length = 64)
	public String getStel() {
		return this.stel;
	}

	public void setStel(String stel) {
		this.stel = stel;
	}

	@Column(name = "senderaddress", length = 256)
	public String getSenderaddress() {
		return this.senderaddress;
	}

	public void setSenderaddress(String senderaddress) {
		this.senderaddress = senderaddress;
	}

	@Column(name = "senderprovince", length = 32)
	public String getSenderprovince() {
		return this.senderprovince;
	}

	public void setSenderprovince(String senderprovince) {
		this.senderprovince = senderprovince;
	}

	@Column(name = "sendercity", length = 32)
	public String getSendercity() {
		return this.sendercity;
	}

	public void setSendercity(String sendercity) {
		this.sendercity = sendercity;
	}

	@Column(name = "senderdistrict", length = 32)
	public String getSenderdistrict() {
		return this.senderdistrict;
	}

	public void setSenderdistrict(String senderdistrict) {
		this.senderdistrict = senderdistrict;
	}

	@Column(name = "signedway", length = 32)
	public String getSignedway() {
		return this.signedway;
	}

	public void setSignedway(String signedway) {
		this.signedway = signedway;
	}

	@Column(name = "staffname", length = 32)
	public String getStaffname() {
		return this.staffname;
	}

	public void setStaffname(String staffname) {
		this.staffname = staffname;
	}

	@Column(name = "stafftel", length = 64)
	public String getStafftel() {
		return this.stafftel;
	}

	public void setStafftel(String stafftel) {
		this.stafftel = stafftel;
	}

	@Column(name = "sendcode", length = 256)
	public String getSendcode() {
		return this.sendcode;
	}

	public void setSendcode(String sendcode) {
		this.sendcode = sendcode;
	}

	@Column(name = "createtime")
	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return this.staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	@Column(name = "totalprice", precision = 12)
	public Double getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(Double totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "expresscharge", precision = 12)
	public Double getExpresscharge() {
		return this.expresscharge;
	}

	public void setExpresscharge(Double expresscharge) {
		this.expresscharge = expresscharge;
	}

	@Column(name = "serverfee", precision = 12)
	public Double getServerfee() {
		return this.serverfee;
	}

	public void setServerfee(Double serverfee) {
		this.serverfee = serverfee;
	}

	@Column(name = "discountfee", precision = 12)
	public Double getDiscountfee() {
		return this.discountfee;
	}

	public void setDiscountfee(Double discountfee) {
		this.discountfee = discountfee;
	}

	@Column(name = "payway", length = 32)
	public String getPayway() {
		return this.payway;
	}

	public void setPayway(String payway) {
		this.payway = payway;
	}

	@Column(name = "payfee", precision = 12)
	public Double getPayfee() {
		return this.payfee;
	}

	public void setPayfee(Double payfee) {
		this.payfee = payfee;
	}

	@Column(name = "serialnum", length = 256)
	public String getSerialnum() {
		return this.serialnum;
	}

	public void setSerialnum(String serialnum) {
		this.serialnum = serialnum;
	}

	@Column(name = "sendstaffname", length = 32)
	public String getSendstaffname() {
		return this.sendstaffname;
	}

	public void setSendstaffname(String sendstaffname) {
		this.sendstaffname = sendstaffname;
	}

	@Column(name = "sendstafftel", length = 64)
	public String getSendstafftel() {
		return this.sendstafftel;
	}

	public void setSendstafftel(String sendstafftel) {
		this.sendstafftel = sendstafftel;
	}

	@Column(name = "sigedname", length = 32)
	public String getSigedname() {
		return this.sigedname;
	}

	public void setSigedname(String sigedname) {
		this.sigedname = sigedname;
	}

	@Column(name = "sigedtel", length = 64)
	public String getSigedtel() {
		return this.sigedtel;
	}

	public void setSigedtel(String sigedtel) {
		this.sigedtel = sigedtel;
	}

	@Column(name = "packagetype", precision = 10)
	public Integer getPackagetype() {
		return this.packagetype;
	}

	public void setPackagetype(Integer packagetype) {
		this.packagetype = packagetype;
	}

	@Column(name = "weight", precision = 12)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	@Column(name = "detailname", length = 256)
	public String getDetailname() {
		return this.detailname;
	}

	public void setDetailname(String detailname) {
		this.detailname = detailname;
	}

	@Column(name = "takeaddress", length = 1024)
	public String getTakeaddress() {
		return this.takeaddress;
	}

	public void setTakeaddress(String takeaddress) {
		this.takeaddress = takeaddress;
	}

	@Column(name = "reserveinfo", length = 1024)
	public String getReserveinfo() {
		return this.reserveinfo;
	}

	public void setReserveinfo(String reserveinfo) {
		this.reserveinfo = reserveinfo;
	}

	@Column(name = "iscancelsend", precision = 10)
	public Integer getIscancelsend() {
		return this.iscancelsend;
	}

	public void setIscancelsend(Integer iscancelsend) {
		this.iscancelsend = iscancelsend;
	}

	@Column(name = "isinsured", precision = 10)
	public Integer getIsinsured() {
		return this.isinsured;
	}

	public void setIsinsured(Integer isinsured) {
		this.isinsured = isinsured;
	}

	@Column(name = "state", length = 32)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "weightinfo", length = 64)
	public String getWeightinfo() {
		return this.weightinfo;
	}

	public void setWeightinfo(String weightinfo) {
		this.weightinfo = weightinfo;
	}

	@Column(name = "dstaffid", length = 32)
	public String getDstaffid() {
		return this.dstaffid;
	}

	public void setDstaffid(String dstaffid) {
		this.dstaffid = dstaffid;
	}

	@Column(name = "suserid", length = 32)
	public String getSuserid() {
		return this.suserid;
	}

	public void setSuserid(String suserid) {
		this.suserid = suserid;
	}

	@Column(name = "asbegin")
	public Timestamp getAsbegin() {
		return this.asbegin;
	}

	public void setAsbegin(Timestamp asbegin) {
		this.asbegin = asbegin;
	}

	@Column(name = "apend")
	public Timestamp getApend() {
		return this.apend;
	}

	public void setApend(Timestamp apend) {
		this.apend = apend;
	}

	@Column(name = "rdtime")
	public Timestamp getRdtime() {
		return this.rdtime;
	}

	public void setRdtime(Timestamp rdtime) {
		this.rdtime = rdtime;
	}

	@Column(name = "dcount", precision = 10)
	public Integer getDcount() {
		return this.dcount;
	}

	public void setDcount(Integer dcount) {
		this.dcount = dcount;
	}
}
