/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "permission", schema = "ewp")
public class Permission implements Serializable {

	private static final long serialVersionUID = -101168854;

	private String  permissionid;
	private String  name;
	private Integer type;
	private Integer status;
	private String  parentid;
	private Integer ordernum;
	private Integer level;
	private Integer orderby;
	private String  action;

	public Permission() {}

	public Permission(Permission value) {
		this.permissionid = value.permissionid;
		this.name = value.name;
		this.type = value.type;
		this.status = value.status;
		this.parentid = value.parentid;
		this.ordernum = value.ordernum;
		this.level = value.level;
		this.orderby = value.orderby;
		this.action = value.action;
	}

	public Permission(
		String  permissionid,
		String  name,
		Integer type,
		Integer status,
		String  parentid,
		Integer ordernum,
		Integer level,
		Integer orderby,
		String  action
	) {
		this.permissionid = permissionid;
		this.name = name;
		this.type = type;
		this.status = status;
		this.parentid = parentid;
		this.ordernum = ordernum;
		this.level = level;
		this.orderby = orderby;
		this.action = action;
	}

	@Id
	@Column(name = "permissionid", unique = true, nullable = false, length = 32)
	public String getPermissionid() {
		return this.permissionid;
	}

	public void setPermissionid(String permissionid) {
		this.permissionid = permissionid;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "status", precision = 10)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "parentid", length = 32)
	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	@Column(name = "ordernum", precision = 10)
	public Integer getOrdernum() {
		return this.ordernum;
	}

	public void setOrdernum(Integer ordernum) {
		this.ordernum = ordernum;
	}

	@Column(name = "level", precision = 10)
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "orderby", precision = 10)
	public Integer getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Integer orderby) {
		this.orderby = orderby;
	}

	@Column(name = "action", length = 1024)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}
}
