/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "staff", schema = "ewp")
public class Staff implements Serializable {

	private static final long serialVersionUID = 1852341135;

	private String    staffid;
	private String    clientid;
	private Integer   type;
	private String    sex;
	private String    username;
	private String    password;
	private Integer   status;
	private Integer   ismaster;
	private String    name;
	private Timestamp lastlogintime;

	public Staff() {}

	public Staff(Staff value) {
		this.staffid = value.staffid;
		this.clientid = value.clientid;
		this.type = value.type;
		this.sex = value.sex;
		this.username = value.username;
		this.password = value.password;
		this.status = value.status;
		this.ismaster = value.ismaster;
		this.name = value.name;
		this.lastlogintime = value.lastlogintime;
	}

	public Staff(
		String    staffid,
		String    clientid,
		Integer   type,
		String    sex,
		String    username,
		String    password,
		Integer   status,
		Integer   ismaster,
		String    name,
		Timestamp lastlogintime
	) {
		this.staffid = staffid;
		this.clientid = clientid;
		this.type = type;
		this.sex = sex;
		this.username = username;
		this.password = password;
		this.status = status;
		this.ismaster = ismaster;
		this.name = name;
		this.lastlogintime = lastlogintime;
	}

	@Id
	@Column(name = "staffid", unique = true, nullable = false, length = 32)
	public String getStaffid() {
		return this.staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	@Column(name = "clientid", length = 32)
	public String getClientid() {
		return this.clientid;
	}

	public void setClientid(String clientid) {
		this.clientid = clientid;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "sex", length = 32)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "username", length = 32)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", precision = 10)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "ismaster", precision = 10)
	public Integer getIsmaster() {
		return this.ismaster;
	}

	public void setIsmaster(Integer ismaster) {
		this.ismaster = ismaster;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lastlogintime")
	public Timestamp getLastlogintime() {
		return this.lastlogintime;
	}

	public void setLastlogintime(Timestamp lastlogintime) {
		this.lastlogintime = lastlogintime;
	}
}
