/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sysexpresstemplate", schema = "ewp")
public class Sysexpresstemplate implements Serializable {

	private static final long serialVersionUID = 2128592720;

	private String  id;
	private String  name;
	private String  image;
	private String  clientid;
	private String  forwardcompanyid;
	private Integer isdefault;
	private String  width;
	private String  height;
	private String  value;
	private Integer needsendcode;

	public Sysexpresstemplate() {}

	public Sysexpresstemplate(Sysexpresstemplate value) {
		this.id = value.id;
		this.name = value.name;
		this.image = value.image;
		this.clientid = value.clientid;
		this.forwardcompanyid = value.forwardcompanyid;
		this.isdefault = value.isdefault;
		this.width = value.width;
		this.height = value.height;
		this.value = value.value;
		this.needsendcode = value.needsendcode;
	}

	public Sysexpresstemplate(
		String  id,
		String  name,
		String  image,
		String  clientid,
		String  forwardcompanyid,
		Integer isdefault,
		String  width,
		String  height,
		String  value,
		Integer needsendcode
	) {
		this.id = id;
		this.name = name;
		this.image = image;
		this.clientid = clientid;
		this.forwardcompanyid = forwardcompanyid;
		this.isdefault = isdefault;
		this.width = width;
		this.height = height;
		this.value = value;
		this.needsendcode = needsendcode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", length = 256)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "clientid", length = 32)
	public String getClientid() {
		return this.clientid;
	}

	public void setClientid(String clientid) {
		this.clientid = clientid;
	}

	@Column(name = "forwardcompanyid", length = 32)
	public String getForwardcompanyid() {
		return this.forwardcompanyid;
	}

	public void setForwardcompanyid(String forwardcompanyid) {
		this.forwardcompanyid = forwardcompanyid;
	}

	@Column(name = "isdefault", precision = 10)
	public Integer getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Integer isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "width", length = 32)
	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	@Column(name = "height", length = 32)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "value", length = 5000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "needsendcode", precision = 10)
	public Integer getNeedsendcode() {
		return this.needsendcode;
	}

	public void setNeedsendcode(Integer needsendcode) {
		this.needsendcode = needsendcode;
	}
}
