/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user", schema = "ewp")
public class User implements Serializable {

	private static final long serialVersionUID = 152470504;

	private String    userid;
	private String    username;
	private String    password;
	private String    nick;
	private Integer   type;
	private String    telphone;
	private String    name;
	private String    image;
	private String    securitycode;
	private Timestamp registertime;
	private Integer   isidentified;
	private Integer   age;
	private String    sex;
	private String    temptel;
	private String    channelid;
	private String    stationcode;
	private String    staffcode;
	private Integer   dtype;
	private String    dserial;

	public User() {}

	public User(User value) {
		this.userid = value.userid;
		this.username = value.username;
		this.password = value.password;
		this.nick = value.nick;
		this.type = value.type;
		this.telphone = value.telphone;
		this.name = value.name;
		this.image = value.image;
		this.securitycode = value.securitycode;
		this.registertime = value.registertime;
		this.isidentified = value.isidentified;
		this.age = value.age;
		this.sex = value.sex;
		this.temptel = value.temptel;
		this.channelid = value.channelid;
		this.stationcode = value.stationcode;
		this.staffcode = value.staffcode;
		this.dtype = value.dtype;
		this.dserial = value.dserial;
	}

	public User(
		String    userid,
		String    username,
		String    password,
		String    nick,
		Integer   type,
		String    telphone,
		String    name,
		String    image,
		String    securitycode,
		Timestamp registertime,
		Integer   isidentified,
		Integer   age,
		String    sex,
		String    temptel,
		String    channelid,
		String    stationcode,
		String    staffcode,
		Integer   dtype,
		String    dserial
	) {
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.nick = nick;
		this.type = type;
		this.telphone = telphone;
		this.name = name;
		this.image = image;
		this.securitycode = securitycode;
		this.registertime = registertime;
		this.isidentified = isidentified;
		this.age = age;
		this.sex = sex;
		this.temptel = temptel;
		this.channelid = channelid;
		this.stationcode = stationcode;
		this.staffcode = staffcode;
		this.dtype = dtype;
		this.dserial = dserial;
	}

	@Id
	@Column(name = "userid", unique = true, nullable = false, length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "username", length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nick", length = 32)
	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "telphone", length = 64)
	public String getTelphone() {
		return this.telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", length = 256)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "securitycode", length = 32)
	public String getSecuritycode() {
		return this.securitycode;
	}

	public void setSecuritycode(String securitycode) {
		this.securitycode = securitycode;
	}

	@Column(name = "registertime")
	public Timestamp getRegistertime() {
		return this.registertime;
	}

	public void setRegistertime(Timestamp registertime) {
		this.registertime = registertime;
	}

	@Column(name = "isidentified", precision = 10)
	public Integer getIsidentified() {
		return this.isidentified;
	}

	public void setIsidentified(Integer isidentified) {
		this.isidentified = isidentified;
	}

	@Column(name = "age", precision = 10)
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "sex", length = 32)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "temptel", length = 64)
	public String getTemptel() {
		return this.temptel;
	}

	public void setTemptel(String temptel) {
		this.temptel = temptel;
	}

	@Column(name = "channelid", length = 64)
	public String getChannelid() {
		return this.channelid;
	}

	public void setChannelid(String channelid) {
		this.channelid = channelid;
	}

	@Column(name = "stationcode", length = 64)
	public String getStationcode() {
		return this.stationcode;
	}

	public void setStationcode(String stationcode) {
		this.stationcode = stationcode;
	}

	@Column(name = "staffcode", length = 64)
	public String getStaffcode() {
		return this.staffcode;
	}

	public void setStaffcode(String staffcode) {
		this.staffcode = staffcode;
	}

	@Column(name = "dtype", precision = 10)
	public Integer getDtype() {
		return this.dtype;
	}

	public void setDtype(Integer dtype) {
		this.dtype = dtype;
	}

	@Column(name = "dserial", length = 128)
	public String getDserial() {
		return this.dserial;
	}

	public void setDserial(String dserial) {
		this.dserial = dserial;
	}
}
