/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.CenterRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Center extends TableImpl<CenterRecord> {

	private static final long serialVersionUID = -344101481;

	/**
	 * The reference instance of <code>ewp.center</code>
	 */
	public static final Center CENTER = new Center();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CenterRecord> getRecordType() {
		return CenterRecord.class;
	}

	/**
	 * The column <code>ewp.center.centerid</code>.
	 */
	public final TableField<CenterRecord, String> CENTERID = createField("centerid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.center.account</code>.
	 */
	public final TableField<CenterRecord, Double> ACCOUNT = createField("account", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.center.coins</code>.
	 */
	public final TableField<CenterRecord, Double> COINS = createField("coins", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.center.level</code>.
	 */
	public final TableField<CenterRecord, String> LEVEL = createField("level", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.userid</code>.
	 */
	public final TableField<CenterRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.integral</code>.
	 */
	public final TableField<CenterRecord, Integer> INTEGRAL = createField("integral", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.center.etime</code>.
	 */
	public final TableField<CenterRecord, String> ETIME = createField("etime", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.eattitude</code>.
	 */
	public final TableField<CenterRecord, String> EATTITUDE = createField("eattitude", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.percentage</code>.
	 */
	public final TableField<CenterRecord, String> PERCENTAGE = createField("percentage", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.countone</code>.
	 */
	public final TableField<CenterRecord, String> COUNTONE = createField("countone", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.counttwo</code>.
	 */
	public final TableField<CenterRecord, String> COUNTTWO = createField("counttwo", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.countthree</code>.
	 */
	public final TableField<CenterRecord, String> COUNTTHREE = createField("countthree", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.countfour</code>.
	 */
	public final TableField<CenterRecord, String> COUNTFOUR = createField("countfour", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.countfive</code>.
	 */
	public final TableField<CenterRecord, String> COUNTFIVE = createField("countfive", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.apercentage</code>.
	 */
	public final TableField<CenterRecord, String> APERCENTAGE = createField("apercentage", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.acountone</code>.
	 */
	public final TableField<CenterRecord, String> ACOUNTONE = createField("acountone", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.acounttwo</code>.
	 */
	public final TableField<CenterRecord, String> ACOUNTTWO = createField("acounttwo", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.acountthree</code>.
	 */
	public final TableField<CenterRecord, String> ACOUNTTHREE = createField("acountthree", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.acountfour</code>.
	 */
	public final TableField<CenterRecord, String> ACOUNTFOUR = createField("acountfour", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.center.acountfive</code>.
	 */
	public final TableField<CenterRecord, String> ACOUNTFIVE = createField("acountfive", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>ewp.center</code> table reference
	 */
	public Center() {
		this("center", null);
	}

	/**
	 * Create an aliased <code>ewp.center</code> table reference
	 */
	public Center(String alias) {
		this(alias, CENTER);
	}

	private Center(String alias, Table<CenterRecord> aliased) {
		this(alias, aliased, null);
	}

	private Center(String alias, Table<CenterRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CenterRecord> getPrimaryKey() {
		return Keys.KEY_CENTER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CenterRecord>> getKeys() {
		return Arrays.<UniqueKey<CenterRecord>>asList(Keys.KEY_CENTER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Center as(String alias) {
		return new Center(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Center rename(String name) {
		return new Center(name, null);
	}
}
