/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.ClientRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client extends TableImpl<ClientRecord> {

	private static final long serialVersionUID = -853243343;

	/**
	 * The reference instance of <code>ewp.client</code>
	 */
	public static final Client CLIENT = new Client();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ClientRecord> getRecordType() {
		return ClientRecord.class;
	}

	/**
	 * The column <code>ewp.client.clientid</code>.
	 */
	public final TableField<ClientRecord, String> CLIENTID = createField("clientid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.client.name</code>.
	 */
	public final TableField<ClientRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.client.type</code>.
	 */
	public final TableField<ClientRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.client.address</code>.
	 */
	public final TableField<ClientRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.client.phone</code>.
	 */
	public final TableField<ClientRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.client.status</code>.
	 */
	public final TableField<ClientRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.client.memo</code>.
	 */
	public final TableField<ClientRecord, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * Create a <code>ewp.client</code> table reference
	 */
	public Client() {
		this("client", null);
	}

	/**
	 * Create an aliased <code>ewp.client</code> table reference
	 */
	public Client(String alias) {
		this(alias, CLIENT);
	}

	private Client(String alias, Table<ClientRecord> aliased) {
		this(alias, aliased, null);
	}

	private Client(String alias, Table<ClientRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ClientRecord> getPrimaryKey() {
		return Keys.KEY_CLIENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ClientRecord>> getKeys() {
		return Arrays.<UniqueKey<ClientRecord>>asList(Keys.KEY_CLIENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Client as(String alias) {
		return new Client(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Client rename(String name) {
		return new Client(name, null);
	}
}
