/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.ImomessageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Imomessage extends TableImpl<ImomessageRecord> {

	private static final long serialVersionUID = 336956258;

	/**
	 * The reference instance of <code>ewp.imomessage</code>
	 */
	public static final Imomessage IMOMESSAGE = new Imomessage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ImomessageRecord> getRecordType() {
		return ImomessageRecord.class;
	}

	/**
	 * The column <code>ewp.imomessage.id</code>.
	 */
	public final TableField<ImomessageRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.imomessage.name</code>.
	 */
	public final TableField<ImomessageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.imomessage.image</code>.
	 */
	public final TableField<ImomessageRecord, String> IMAGE = createField("image", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.imomessage.userid</code>.
	 */
	public final TableField<ImomessageRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.imomessage.orderid</code>.
	 */
	public final TableField<ImomessageRecord, String> ORDERID = createField("orderid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.imomessage.evatype</code>.
	 */
	public final TableField<ImomessageRecord, String> EVATYPE = createField("evatype", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.imomessage.createtime</code>.
	 */
	public final TableField<ImomessageRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.imomessage.type</code>.
	 */
	public final TableField<ImomessageRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.imomessage.text</code>.
	 */
	public final TableField<ImomessageRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>ewp.imomessage</code> table reference
	 */
	public Imomessage() {
		this("imomessage", null);
	}

	/**
	 * Create an aliased <code>ewp.imomessage</code> table reference
	 */
	public Imomessage(String alias) {
		this(alias, IMOMESSAGE);
	}

	private Imomessage(String alias, Table<ImomessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Imomessage(String alias, Table<ImomessageRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ImomessageRecord> getPrimaryKey() {
		return Keys.KEY_IMOMESSAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ImomessageRecord>> getKeys() {
		return Arrays.<UniqueKey<ImomessageRecord>>asList(Keys.KEY_IMOMESSAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Imomessage as(String alias) {
		return new Imomessage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Imomessage rename(String name) {
		return new Imomessage(name, null);
	}
}
