/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.MessageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message extends TableImpl<MessageRecord> {

	private static final long serialVersionUID = 1929898053;

	/**
	 * The reference instance of <code>ewp.message</code>
	 */
	public static final Message MESSAGE = new Message();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MessageRecord> getRecordType() {
		return MessageRecord.class;
	}

	/**
	 * The column <code>ewp.message.messageid</code>.
	 */
	public final TableField<MessageRecord, String> MESSAGEID = createField("messageid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.message.type</code>.
	 */
	public final TableField<MessageRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.userid</code>.
	 */
	public final TableField<MessageRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.staffid</code>.
	 */
	public final TableField<MessageRecord, String> STAFFID = createField("staffid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.context</code>.
	 */
	public final TableField<MessageRecord, String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.message.orderid</code>.
	 */
	public final TableField<MessageRecord, String> ORDERID = createField("orderid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.sendtype</code>.
	 */
	public final TableField<MessageRecord, String> SENDTYPE = createField("sendtype", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.state</code>.
	 */
	public final TableField<MessageRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.message.time</code>.
	 */
	public final TableField<MessageRecord, Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.message.issms</code>.
	 */
	public final TableField<MessageRecord, Integer> ISSMS = createField("issms", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>ewp.message.mobile</code>.
	 */
	public final TableField<MessageRecord, String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.message.ostate</code>.
	 */
	public final TableField<MessageRecord, String> OSTATE = createField("ostate", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.targetid</code>.
	 */
	public final TableField<MessageRecord, String> TARGETID = createField("targetid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.message.pushtype</code>.
	 */
	public final TableField<MessageRecord, Integer> PUSHTYPE = createField("pushtype", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>ewp.message</code> table reference
	 */
	public Message() {
		this("message", null);
	}

	/**
	 * Create an aliased <code>ewp.message</code> table reference
	 */
	public Message(String alias) {
		this(alias, MESSAGE);
	}

	private Message(String alias, Table<MessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Message(String alias, Table<MessageRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MessageRecord> getPrimaryKey() {
		return Keys.KEY_MESSAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MessageRecord>> getKeys() {
		return Arrays.<UniqueKey<MessageRecord>>asList(Keys.KEY_MESSAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Message as(String alias) {
		return new Message(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Message rename(String name) {
		return new Message(name, null);
	}
}
