/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.RelatedinfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relatedinfo extends TableImpl<RelatedinfoRecord> {

	private static final long serialVersionUID = -566441610;

	/**
	 * The reference instance of <code>ewp.relatedinfo</code>
	 */
	public static final Relatedinfo RELATEDINFO = new Relatedinfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RelatedinfoRecord> getRecordType() {
		return RelatedinfoRecord.class;
	}

	/**
	 * The column <code>ewp.relatedinfo.relatedinfoid</code>.
	 */
	public final TableField<RelatedinfoRecord, String> RELATEDINFOID = createField("relatedinfoid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.relatedinfo.orderid</code>.
	 */
	public final TableField<RelatedinfoRecord, String> ORDERID = createField("orderid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.relatedinfo.picture</code>.
	 */
	public final TableField<RelatedinfoRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.relatedinfo.userid</code>.
	 */
	public final TableField<RelatedinfoRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.relatedinfo.staffid</code>.
	 */
	public final TableField<RelatedinfoRecord, String> STAFFID = createField("staffid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.relatedinfo.memo</code>.
	 */
	public final TableField<RelatedinfoRecord, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.relatedinfo.sound</code>.
	 */
	public final TableField<RelatedinfoRecord, String> SOUND = createField("sound", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.relatedinfo.type</code>.
	 */
	public final TableField<RelatedinfoRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>ewp.relatedinfo</code> table reference
	 */
	public Relatedinfo() {
		this("relatedinfo", null);
	}

	/**
	 * Create an aliased <code>ewp.relatedinfo</code> table reference
	 */
	public Relatedinfo(String alias) {
		this(alias, RELATEDINFO);
	}

	private Relatedinfo(String alias, Table<RelatedinfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Relatedinfo(String alias, Table<RelatedinfoRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RelatedinfoRecord> getPrimaryKey() {
		return Keys.KEY_RELATEDINFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RelatedinfoRecord>> getKeys() {
		return Arrays.<UniqueKey<RelatedinfoRecord>>asList(Keys.KEY_RELATEDINFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Relatedinfo as(String alias) {
		return new Relatedinfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Relatedinfo rename(String name) {
		return new Relatedinfo(name, null);
	}
}
