/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.StaffpermissionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staffpermission extends TableImpl<StaffpermissionRecord> {

	private static final long serialVersionUID = 2146439095;

	/**
	 * The reference instance of <code>ewp.staffpermission</code>
	 */
	public static final Staffpermission STAFFPERMISSION = new Staffpermission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StaffpermissionRecord> getRecordType() {
		return StaffpermissionRecord.class;
	}

	/**
	 * The column <code>ewp.staffpermission.staffpermissionid</code>.
	 */
	public final TableField<StaffpermissionRecord, String> STAFFPERMISSIONID = createField("staffpermissionid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.staffpermission.staffid</code>.
	 */
	public final TableField<StaffpermissionRecord, String> STAFFID = createField("staffid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staffpermission.roleid</code>.
	 */
	public final TableField<StaffpermissionRecord, String> ROLEID = createField("roleid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staffpermission.permissionid</code>.
	 */
	public final TableField<StaffpermissionRecord, String> PERMISSIONID = createField("permissionid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>ewp.staffpermission</code> table reference
	 */
	public Staffpermission() {
		this("staffpermission", null);
	}

	/**
	 * Create an aliased <code>ewp.staffpermission</code> table reference
	 */
	public Staffpermission(String alias) {
		this(alias, STAFFPERMISSION);
	}

	private Staffpermission(String alias, Table<StaffpermissionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Staffpermission(String alias, Table<StaffpermissionRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StaffpermissionRecord> getPrimaryKey() {
		return Keys.KEY_STAFFPERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StaffpermissionRecord>> getKeys() {
		return Arrays.<UniqueKey<StaffpermissionRecord>>asList(Keys.KEY_STAFFPERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Staffpermission as(String alias) {
		return new Staffpermission(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Staffpermission rename(String name) {
		return new Staffpermission(name, null);
	}
}
