/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.StaffRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff extends TableImpl<StaffRecord> {

	private static final long serialVersionUID = 1058474248;

	/**
	 * The reference instance of <code>ewp.staff</code>
	 */
	public static final Staff STAFF = new Staff();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StaffRecord> getRecordType() {
		return StaffRecord.class;
	}

	/**
	 * The column <code>ewp.staff.staffid</code>.
	 */
	public final TableField<StaffRecord, String> STAFFID = createField("staffid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.staff.clientid</code>.
	 */
	public final TableField<StaffRecord, String> CLIENTID = createField("clientid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staff.type</code>.
	 */
	public final TableField<StaffRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.staff.sex</code>.
	 */
	public final TableField<StaffRecord, String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staff.username</code>.
	 */
	public final TableField<StaffRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staff.password</code>.
	 */
	public final TableField<StaffRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staff.status</code>.
	 */
	public final TableField<StaffRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.staff.ismaster</code>.
	 */
	public final TableField<StaffRecord, Integer> ISMASTER = createField("ismaster", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.staff.name</code>.
	 */
	public final TableField<StaffRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.staff.lastlogintime</code>.
	 */
	public final TableField<StaffRecord, Timestamp> LASTLOGINTIME = createField("lastlogintime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ewp.staff</code> table reference
	 */
	public Staff() {
		this("staff", null);
	}

	/**
	 * Create an aliased <code>ewp.staff</code> table reference
	 */
	public Staff(String alias) {
		this(alias, STAFF);
	}

	private Staff(String alias, Table<StaffRecord> aliased) {
		this(alias, aliased, null);
	}

	private Staff(String alias, Table<StaffRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StaffRecord> getPrimaryKey() {
		return Keys.KEY_STAFF_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StaffRecord>> getKeys() {
		return Arrays.<UniqueKey<StaffRecord>>asList(Keys.KEY_STAFF_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Staff as(String alias) {
		return new Staff(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Staff rename(String name) {
		return new Staff(name, null);
	}
}
