/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.SysexpresstemplateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sysexpresstemplate extends TableImpl<SysexpresstemplateRecord> {

	private static final long serialVersionUID = -983173245;

	/**
	 * The reference instance of <code>ewp.sysexpresstemplate</code>
	 */
	public static final Sysexpresstemplate SYSEXPRESSTEMPLATE = new Sysexpresstemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SysexpresstemplateRecord> getRecordType() {
		return SysexpresstemplateRecord.class;
	}

	/**
	 * The column <code>ewp.sysexpresstemplate.id</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.name</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.image</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> IMAGE = createField("image", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.clientid</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> CLIENTID = createField("clientid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.forwardcompanyid</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> FORWARDCOMPANYID = createField("forwardcompanyid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.isdefault</code>.
	 */
	public final TableField<SysexpresstemplateRecord, Integer> ISDEFAULT = createField("isdefault", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.width</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> WIDTH = createField("width", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.height</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> HEIGHT = createField("height", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.value</code>.
	 */
	public final TableField<SysexpresstemplateRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(5000), this, "");

	/**
	 * The column <code>ewp.sysexpresstemplate.needsendcode</code>.
	 */
	public final TableField<SysexpresstemplateRecord, Integer> NEEDSENDCODE = createField("needsendcode", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>ewp.sysexpresstemplate</code> table reference
	 */
	public Sysexpresstemplate() {
		this("sysexpresstemplate", null);
	}

	/**
	 * Create an aliased <code>ewp.sysexpresstemplate</code> table reference
	 */
	public Sysexpresstemplate(String alias) {
		this(alias, SYSEXPRESSTEMPLATE);
	}

	private Sysexpresstemplate(String alias, Table<SysexpresstemplateRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sysexpresstemplate(String alias, Table<SysexpresstemplateRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SysexpresstemplateRecord> getPrimaryKey() {
		return Keys.KEY_SYSEXPRESSTEMPLATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SysexpresstemplateRecord>> getKeys() {
		return Arrays.<UniqueKey<SysexpresstemplateRecord>>asList(Keys.KEY_SYSEXPRESSTEMPLATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Sysexpresstemplate as(String alias) {
		return new Sysexpresstemplate(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Sysexpresstemplate rename(String name) {
		return new Sysexpresstemplate(name, null);
	}
}
