/**
 * This class is generated by jOOQ
 */
package com.wfs.model.tables;


import com.wfs.model.Ewp;
import com.wfs.model.Keys;
import com.wfs.model.tables.records.TimeserverRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Timeserver extends TableImpl<TimeserverRecord> {

	private static final long serialVersionUID = -1833248401;

	/**
	 * The reference instance of <code>ewp.timeserver</code>
	 */
	public static final Timeserver TIMESERVER = new Timeserver();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TimeserverRecord> getRecordType() {
		return TimeserverRecord.class;
	}

	/**
	 * The column <code>ewp.timeserver.timeserverid</code>.
	 */
	public final TableField<TimeserverRecord, String> TIMESERVERID = createField("timeserverid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.timeserver.duration</code>.
	 */
	public final TableField<TimeserverRecord, Double> DURATION = createField("duration", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.timeserver.money</code>.
	 */
	public final TableField<TimeserverRecord, Double> MONEY = createField("money", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.timeserver.name</code>.
	 */
	public final TableField<TimeserverRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.timeserver.memo</code>.
	 */
	public final TableField<TimeserverRecord, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.timeserver.isdefault</code>.
	 */
	public final TableField<TimeserverRecord, Integer> ISDEFAULT = createField("isdefault", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>ewp.timeserver</code> table reference
	 */
	public Timeserver() {
		this("timeserver", null);
	}

	/**
	 * Create an aliased <code>ewp.timeserver</code> table reference
	 */
	public Timeserver(String alias) {
		this(alias, TIMESERVER);
	}

	private Timeserver(String alias, Table<TimeserverRecord> aliased) {
		this(alias, aliased, null);
	}

	private Timeserver(String alias, Table<TimeserverRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TimeserverRecord> getPrimaryKey() {
		return Keys.KEY_TIMESERVER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TimeserverRecord>> getKeys() {
		return Arrays.<UniqueKey<TimeserverRecord>>asList(Keys.KEY_TIMESERVER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timeserver as(String alias) {
		return new Timeserver(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Timeserver rename(String name) {
		return new Timeserver(name, null);
	}
}
