/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "databasechangelog", schema = "ewp", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"ID", "AUTHOR", "FILENAME"})
})
public class Databasechangelog implements Serializable {

	private static final long serialVersionUID = -688912927;

	private String    id;
	private String    author;
	private String    filename;
	private Timestamp dateexecuted;
	private String    md5sum;
	private String    description;
	private String    comments;
	private String    tag;
	private String    liquibase;

	public Databasechangelog() {}

	public Databasechangelog(Databasechangelog value) {
		this.id = value.id;
		this.author = value.author;
		this.filename = value.filename;
		this.dateexecuted = value.dateexecuted;
		this.md5sum = value.md5sum;
		this.description = value.description;
		this.comments = value.comments;
		this.tag = value.tag;
		this.liquibase = value.liquibase;
	}

	public Databasechangelog(
		String    id,
		String    author,
		String    filename,
		Timestamp dateexecuted,
		String    md5sum,
		String    description,
		String    comments,
		String    tag,
		String    liquibase
	) {
		this.id = id;
		this.author = author;
		this.filename = filename;
		this.dateexecuted = dateexecuted;
		this.md5sum = md5sum;
		this.description = description;
		this.comments = comments;
		this.tag = tag;
		this.liquibase = liquibase;
	}

	@Column(name = "ID", nullable = false, length = 63)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "AUTHOR", nullable = false, length = 63)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "FILENAME", nullable = false, length = 200)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "DATEEXECUTED", nullable = false)
	public Timestamp getDateexecuted() {
		return this.dateexecuted;
	}

	public void setDateexecuted(Timestamp dateexecuted) {
		this.dateexecuted = dateexecuted;
	}

	@Column(name = "MD5SUM", length = 32)
	public String getMd5sum() {
		return this.md5sum;
	}

	public void setMd5sum(String md5sum) {
		this.md5sum = md5sum;
	}

	@Column(name = "DESCRIPTION", length = 255)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "COMMENTS", length = 255)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "TAG", length = 255)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "LIQUIBASE", length = 10)
	public String getLiquibase() {
		return this.liquibase;
	}

	public void setLiquibase(String liquibase) {
		this.liquibase = liquibase;
	}
}
