/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "message", schema = "ewp")
public class Message implements Serializable {

	private static final long serialVersionUID = 216217997;

	private String    messageid;
	private String    type;
	private String    userid;
	private String    staffid;
	private String    context;
	private String    orderid;
	private String    sendtype;
	private Integer   state;
	private Timestamp time;
	private Integer   issms;
	private String    mobile;
	private String    ostate;
	private String    targetid;
	private Integer   pushtype;

	public Message() {}

	public Message(Message value) {
		this.messageid = value.messageid;
		this.type = value.type;
		this.userid = value.userid;
		this.staffid = value.staffid;
		this.context = value.context;
		this.orderid = value.orderid;
		this.sendtype = value.sendtype;
		this.state = value.state;
		this.time = value.time;
		this.issms = value.issms;
		this.mobile = value.mobile;
		this.ostate = value.ostate;
		this.targetid = value.targetid;
		this.pushtype = value.pushtype;
	}

	public Message(
		String    messageid,
		String    type,
		String    userid,
		String    staffid,
		String    context,
		String    orderid,
		String    sendtype,
		Integer   state,
		Timestamp time,
		Integer   issms,
		String    mobile,
		String    ostate,
		String    targetid,
		Integer   pushtype
	) {
		this.messageid = messageid;
		this.type = type;
		this.userid = userid;
		this.staffid = staffid;
		this.context = context;
		this.orderid = orderid;
		this.sendtype = sendtype;
		this.state = state;
		this.time = time;
		this.issms = issms;
		this.mobile = mobile;
		this.ostate = ostate;
		this.targetid = targetid;
		this.pushtype = pushtype;
	}

	@Id
	@Column(name = "messageid", unique = true, nullable = false, length = 32)
	public String getMessageid() {
		return this.messageid;
	}

	public void setMessageid(String messageid) {
		this.messageid = messageid;
	}

	@Column(name = "type", length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return this.staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	@Column(name = "context", length = 256)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "sendtype", length = 32)
	public String getSendtype() {
		return this.sendtype;
	}

	public void setSendtype(String sendtype) {
		this.sendtype = sendtype;
	}

	@Column(name = "state", precision = 10)
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "time")
	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	@Column(name = "issms", precision = 10)
	public Integer getIssms() {
		return this.issms;
	}

	public void setIssms(Integer issms) {
		this.issms = issms;
	}

	@Column(name = "mobile", length = 64)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ostate", length = 32)
	public String getOstate() {
		return this.ostate;
	}

	public void setOstate(String ostate) {
		this.ostate = ostate;
	}

	@Column(name = "targetid", length = 32)
	public String getTargetid() {
		return this.targetid;
	}

	public void setTargetid(String targetid) {
		this.targetid = targetid;
	}

	@Column(name = "pushtype", precision = 10)
	public Integer getPushtype() {
		return this.pushtype;
	}

	public void setPushtype(Integer pushtype) {
		this.pushtype = pushtype;
	}
}
