/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "note", schema = "ewp")
public class Note implements Serializable {

	private static final long serialVersionUID = -417617823;

	private String noteid;
	private String name;
	private String context;
	private String userid;

	public Note() {}

	public Note(Note value) {
		this.noteid = value.noteid;
		this.name = value.name;
		this.context = value.context;
		this.userid = value.userid;
	}

	public Note(
		String noteid,
		String name,
		String context,
		String userid
	) {
		this.noteid = noteid;
		this.name = name;
		this.context = context;
		this.userid = userid;
	}

	@Id
	@Column(name = "noteid", unique = true, nullable = false, length = 32)
	public String getNoteid() {
		return this.noteid;
	}

	public void setNoteid(String noteid) {
		this.noteid = noteid;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "context", length = 256)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
}
