/**
 * This class is generated by jOOQ
 */
package com.kee.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "relatedinfo", schema = "ewp")
public class Relatedinfo implements Serializable {

	private static final long serialVersionUID = 2109467127;

	private String  relatedinfoid;
	private String  orderid;
	private String  picture;
	private String  userid;
	private String  staffid;
	private String  memo;
	private String  sound;
	private Integer type;

	public Relatedinfo() {}

	public Relatedinfo(Relatedinfo value) {
		this.relatedinfoid = value.relatedinfoid;
		this.orderid = value.orderid;
		this.picture = value.picture;
		this.userid = value.userid;
		this.staffid = value.staffid;
		this.memo = value.memo;
		this.sound = value.sound;
		this.type = value.type;
	}

	public Relatedinfo(
		String  relatedinfoid,
		String  orderid,
		String  picture,
		String  userid,
		String  staffid,
		String  memo,
		String  sound,
		Integer type
	) {
		this.relatedinfoid = relatedinfoid;
		this.orderid = orderid;
		this.picture = picture;
		this.userid = userid;
		this.staffid = staffid;
		this.memo = memo;
		this.sound = sound;
		this.type = type;
	}

	@Id
	@Column(name = "relatedinfoid", unique = true, nullable = false, length = 32)
	public String getRelatedinfoid() {
		return this.relatedinfoid;
	}

	public void setRelatedinfoid(String relatedinfoid) {
		this.relatedinfoid = relatedinfoid;
	}

	@Column(name = "orderid", length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "picture", length = 256)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "staffid", length = 32)
	public String getStaffid() {
		return this.staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	@Column(name = "memo", length = 256)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "sound", length = 256)
	public String getSound() {
		return this.sound;
	}

	public void setSound(String sound) {
		this.sound = sound;
	}

	@Column(name = "type", precision = 10)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
}
