/**
 * This class is generated by jOOQ
 */
package cn.kee.model.tables;


import com.kee.model.tables.records.BusinesslibraryRecord;

import cn.kee.model.Ewp;
import cn.kee.model.Keys;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Businesslibrary extends TableImpl<BusinesslibraryRecord> {

	private static final long serialVersionUID = 4766024;

	/**
	 * The reference instance of <code>ewp.businesslibrary</code>
	 */
	public static final Businesslibrary BUSINESSLIBRARY = new Businesslibrary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BusinesslibraryRecord> getRecordType() {
		return BusinesslibraryRecord.class;
	}

	/**
	 * The column <code>ewp.businesslibrary.businesslibraryid</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> BUSINESSLIBRARYID = createField("businesslibraryid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.businesslibrary.orderid</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> ORDERID = createField("orderid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.businesslibrary.action</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>ewp.businesslibrary.createtime</code>.
	 */
	public final TableField<BusinesslibraryRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.businesslibrary.userid</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.businesslibrary.staffid</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> STAFFID = createField("staffid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.businesslibrary.memo</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.businesslibrary.code</code>.
	 */
	public final TableField<BusinesslibraryRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>ewp.businesslibrary</code> table reference
	 */
	public Businesslibrary() {
		this("businesslibrary", null);
	}

	/**
	 * Create an aliased <code>ewp.businesslibrary</code> table reference
	 */
	public Businesslibrary(String alias) {
		this(alias, BUSINESSLIBRARY);
	}

	private Businesslibrary(String alias, Table<BusinesslibraryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Businesslibrary(String alias, Table<BusinesslibraryRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BusinesslibraryRecord> getPrimaryKey() {
		return Keys.KEY_BUSINESSLIBRARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BusinesslibraryRecord>> getKeys() {
		return Arrays.<UniqueKey<BusinesslibraryRecord>>asList(Keys.KEY_BUSINESSLIBRARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Businesslibrary as(String alias) {
		return new Businesslibrary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Businesslibrary rename(String name) {
		return new Businesslibrary(name, null);
	}
}
