/**
 * This class is generated by jOOQ
 */
package cn.kee.model.tables;


import com.kee.model.tables.records.CouponRecord;

import cn.kee.model.Ewp;
import cn.kee.model.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coupon extends TableImpl<CouponRecord> {

	private static final long serialVersionUID = 181744216;

	/**
	 * The reference instance of <code>ewp.coupon</code>
	 */
	public static final Coupon COUPON = new Coupon();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CouponRecord> getRecordType() {
		return CouponRecord.class;
	}

	/**
	 * The column <code>ewp.coupon.couponid</code>.
	 */
	public final TableField<CouponRecord, String> COUPONID = createField("couponid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.coupon.name</code>.
	 */
	public final TableField<CouponRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.coupon.picture</code>.
	 */
	public final TableField<CouponRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.coupon.momey</code>.
	 */
	public final TableField<CouponRecord, Double> MOMEY = createField("momey", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.coupon.context</code>.
	 */
	public final TableField<CouponRecord, String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.coupon.userid</code>.
	 */
	public final TableField<CouponRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>ewp.coupon</code> table reference
	 */
	public Coupon() {
		this("coupon", null);
	}

	/**
	 * Create an aliased <code>ewp.coupon</code> table reference
	 */
	public Coupon(String alias) {
		this(alias, COUPON);
	}

	private Coupon(String alias, Table<CouponRecord> aliased) {
		this(alias, aliased, null);
	}

	private Coupon(String alias, Table<CouponRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CouponRecord> getPrimaryKey() {
		return Keys.KEY_COUPON_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CouponRecord>> getKeys() {
		return Arrays.<UniqueKey<CouponRecord>>asList(Keys.KEY_COUPON_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Coupon as(String alias) {
		return new Coupon(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Coupon rename(String name) {
		return new Coupon(name, null);
	}
}
