/**
 * This class is generated by jOOQ
 */
package cn.kee.model.tables;


import com.kee.model.tables.records.ForwardcompanyRecord;

import cn.kee.model.Ewp;
import cn.kee.model.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Forwardcompany extends TableImpl<ForwardcompanyRecord> {

	private static final long serialVersionUID = -1629853959;

	/**
	 * The reference instance of <code>ewp.forwardcompany</code>
	 */
	public static final Forwardcompany FORWARDCOMPANY = new Forwardcompany();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ForwardcompanyRecord> getRecordType() {
		return ForwardcompanyRecord.class;
	}

	/**
	 * The column <code>ewp.forwardcompany.id</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.forwardcompany.name</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.forwardcompany.type</code>.
	 */
	public final TableField<ForwardcompanyRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.forwardcompany.memo</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.forwardcompany.code</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.forwardcompany.sortno</code>.
	 */
	public final TableField<ForwardcompanyRecord, Integer> SORTNO = createField("sortno", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.forwardcompany.templateimgurl</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> TEMPLATEIMGURL = createField("templateimgurl", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>ewp.forwardcompany.pagewidth</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> PAGEWIDTH = createField("pagewidth", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.forwardcompany.pageheight</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> PAGEHEIGHT = createField("pageheight", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.forwardcompany.templatevalue</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> TEMPLATEVALUE = createField("templatevalue", org.jooq.impl.SQLDataType.VARCHAR.length(5000), this, "");

	/**
	 * The column <code>ewp.forwardcompany.shortname</code>.
	 */
	public final TableField<ForwardcompanyRecord, String> SHORTNAME = createField("shortname", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>ewp.forwardcompany</code> table reference
	 */
	public Forwardcompany() {
		this("forwardcompany", null);
	}

	/**
	 * Create an aliased <code>ewp.forwardcompany</code> table reference
	 */
	public Forwardcompany(String alias) {
		this(alias, FORWARDCOMPANY);
	}

	private Forwardcompany(String alias, Table<ForwardcompanyRecord> aliased) {
		this(alias, aliased, null);
	}

	private Forwardcompany(String alias, Table<ForwardcompanyRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ForwardcompanyRecord> getPrimaryKey() {
		return Keys.KEY_FORWARDCOMPANY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ForwardcompanyRecord>> getKeys() {
		return Arrays.<UniqueKey<ForwardcompanyRecord>>asList(Keys.KEY_FORWARDCOMPANY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Forwardcompany as(String alias) {
		return new Forwardcompany(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Forwardcompany rename(String name) {
		return new Forwardcompany(name, null);
	}
}
