/**
 * This class is generated by jOOQ
 */
package cn.kee.model.tables;


import com.kee.model.tables.records.NoteRecord;

import cn.kee.model.Ewp;
import cn.kee.model.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Note extends TableImpl<NoteRecord> {

	private static final long serialVersionUID = -2046029136;

	/**
	 * The reference instance of <code>ewp.note</code>
	 */
	public static final Note NOTE = new Note();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NoteRecord> getRecordType() {
		return NoteRecord.class;
	}

	/**
	 * The column <code>ewp.note.noteid</code>.
	 */
	public final TableField<NoteRecord, String> NOTEID = createField("noteid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.note.name</code>.
	 */
	public final TableField<NoteRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.note.context</code>.
	 */
	public final TableField<NoteRecord, String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.note.userid</code>.
	 */
	public final TableField<NoteRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>ewp.note</code> table reference
	 */
	public Note() {
		this("note", null);
	}

	/**
	 * Create an aliased <code>ewp.note</code> table reference
	 */
	public Note(String alias) {
		this(alias, NOTE);
	}

	private Note(String alias, Table<NoteRecord> aliased) {
		this(alias, aliased, null);
	}

	private Note(String alias, Table<NoteRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NoteRecord> getPrimaryKey() {
		return Keys.KEY_NOTE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NoteRecord>> getKeys() {
		return Arrays.<UniqueKey<NoteRecord>>asList(Keys.KEY_NOTE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Note as(String alias) {
		return new Note(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Note rename(String name) {
		return new Note(name, null);
	}
}
