/**
 * This class is generated by jOOQ
 */
package cn.kee.model.tables;


import com.kee.model.tables.records.OrderRecord;

import cn.kee.model.Ewp;
import cn.kee.model.Keys;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order extends TableImpl<OrderRecord> {

	private static final long serialVersionUID = -1427442171;

	/**
	 * The reference instance of <code>ewp.order</code>
	 */
	public static final Order ORDER = new Order();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<OrderRecord> getRecordType() {
		return OrderRecord.class;
	}

	/**
	 * The column <code>ewp.order.orderid</code>.
	 */
	public final TableField<OrderRecord, String> ORDERID = createField("orderid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.order.consignee</code>.
	 */
	public final TableField<OrderRecord, String> CONSIGNEE = createField("consignee", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.telphone</code>.
	 */
	public final TableField<OrderRecord, String> TELPHONE = createField("telphone", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.order.address</code>.
	 */
	public final TableField<OrderRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.receiveprovince</code>.
	 */
	public final TableField<OrderRecord, String> RECEIVEPROVINCE = createField("receiveprovince", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.receivecity</code>.
	 */
	public final TableField<OrderRecord, String> RECEIVECITY = createField("receivecity", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.receivedistrict</code>.
	 */
	public final TableField<OrderRecord, String> RECEIVEDISTRICT = createField("receivedistrict", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.sender</code>.
	 */
	public final TableField<OrderRecord, String> SENDER = createField("sender", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.stel</code>.
	 */
	public final TableField<OrderRecord, String> STEL = createField("stel", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.order.senderaddress</code>.
	 */
	public final TableField<OrderRecord, String> SENDERADDRESS = createField("senderaddress", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.senderprovince</code>.
	 */
	public final TableField<OrderRecord, String> SENDERPROVINCE = createField("senderprovince", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.sendercity</code>.
	 */
	public final TableField<OrderRecord, String> SENDERCITY = createField("sendercity", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.senderdistrict</code>.
	 */
	public final TableField<OrderRecord, String> SENDERDISTRICT = createField("senderdistrict", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.signedway</code>.
	 */
	public final TableField<OrderRecord, String> SIGNEDWAY = createField("signedway", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.staffname</code>.
	 */
	public final TableField<OrderRecord, String> STAFFNAME = createField("staffname", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.stafftel</code>.
	 */
	public final TableField<OrderRecord, String> STAFFTEL = createField("stafftel", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.order.sendcode</code>.
	 */
	public final TableField<OrderRecord, String> SENDCODE = createField("sendcode", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.createtime</code>.
	 */
	public final TableField<OrderRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.order.userid</code>.
	 */
	public final TableField<OrderRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.staffid</code>.
	 */
	public final TableField<OrderRecord, String> STAFFID = createField("staffid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.totalprice</code>.
	 */
	public final TableField<OrderRecord, Double> TOTALPRICE = createField("totalprice", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.order.expresscharge</code>.
	 */
	public final TableField<OrderRecord, Double> EXPRESSCHARGE = createField("expresscharge", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.order.serverfee</code>.
	 */
	public final TableField<OrderRecord, Double> SERVERFEE = createField("serverfee", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.order.discountfee</code>.
	 */
	public final TableField<OrderRecord, Double> DISCOUNTFEE = createField("discountfee", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.order.payway</code>.
	 */
	public final TableField<OrderRecord, String> PAYWAY = createField("payway", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.payfee</code>.
	 */
	public final TableField<OrderRecord, Double> PAYFEE = createField("payfee", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.order.serialnum</code>.
	 */
	public final TableField<OrderRecord, String> SERIALNUM = createField("serialnum", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.sendstaffname</code>.
	 */
	public final TableField<OrderRecord, String> SENDSTAFFNAME = createField("sendstaffname", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.sendstafftel</code>.
	 */
	public final TableField<OrderRecord, String> SENDSTAFFTEL = createField("sendstafftel", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.order.sigedname</code>.
	 */
	public final TableField<OrderRecord, String> SIGEDNAME = createField("sigedname", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.sigedtel</code>.
	 */
	public final TableField<OrderRecord, String> SIGEDTEL = createField("sigedtel", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.order.packagetype</code>.
	 */
	public final TableField<OrderRecord, Integer> PACKAGETYPE = createField("packagetype", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.order.weight</code>.
	 */
	public final TableField<OrderRecord, Double> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ewp.order.detailname</code>.
	 */
	public final TableField<OrderRecord, String> DETAILNAME = createField("detailname", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ewp.order.takeaddress</code>.
	 */
	public final TableField<OrderRecord, String> TAKEADDRESS = createField("takeaddress", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>ewp.order.reserveinfo</code>.
	 */
	public final TableField<OrderRecord, String> RESERVEINFO = createField("reserveinfo", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>ewp.order.iscancelsend</code>.
	 */
	public final TableField<OrderRecord, Integer> ISCANCELSEND = createField("iscancelsend", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>ewp.order.isinsured</code>.
	 */
	public final TableField<OrderRecord, Integer> ISINSURED = createField("isinsured", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>ewp.order.state</code>.
	 */
	public final TableField<OrderRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.weightinfo</code>.
	 */
	public final TableField<OrderRecord, String> WEIGHTINFO = createField("weightinfo", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ewp.order.dstaffid</code>.
	 */
	public final TableField<OrderRecord, String> DSTAFFID = createField("dstaffid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.suserid</code>.
	 */
	public final TableField<OrderRecord, String> SUSERID = createField("suserid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.order.asbegin</code>.
	 */
	public final TableField<OrderRecord, Timestamp> ASBEGIN = createField("asbegin", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.order.apend</code>.
	 */
	public final TableField<OrderRecord, Timestamp> APEND = createField("apend", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.order.rdtime</code>.
	 */
	public final TableField<OrderRecord, Timestamp> RDTIME = createField("rdtime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ewp.order.dcount</code>.
	 */
	public final TableField<OrderRecord, Integer> DCOUNT = createField("dcount", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>ewp.order</code> table reference
	 */
	public Order() {
		this("order", null);
	}

	/**
	 * Create an aliased <code>ewp.order</code> table reference
	 */
	public Order(String alias) {
		this(alias, ORDER);
	}

	private Order(String alias, Table<OrderRecord> aliased) {
		this(alias, aliased, null);
	}

	private Order(String alias, Table<OrderRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<OrderRecord> getPrimaryKey() {
		return Keys.KEY_ORDER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<OrderRecord>> getKeys() {
		return Arrays.<UniqueKey<OrderRecord>>asList(Keys.KEY_ORDER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Order as(String alias) {
		return new Order(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Order rename(String name) {
		return new Order(name, null);
	}
}
