/**
 * This class is generated by jOOQ
 */
package cn.kee.model.tables;


import com.kee.model.tables.records.PermissionRecord;

import cn.kee.model.Ewp;
import cn.kee.model.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permission extends TableImpl<PermissionRecord> {

	private static final long serialVersionUID = 1135416920;

	/**
	 * The reference instance of <code>ewp.permission</code>
	 */
	public static final Permission PERMISSION = new Permission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PermissionRecord> getRecordType() {
		return PermissionRecord.class;
	}

	/**
	 * The column <code>ewp.permission.permissionid</code>.
	 */
	public final TableField<PermissionRecord, String> PERMISSIONID = createField("permissionid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ewp.permission.name</code>.
	 */
	public final TableField<PermissionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.permission.type</code>.
	 */
	public final TableField<PermissionRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.permission.status</code>.
	 */
	public final TableField<PermissionRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.permission.parentid</code>.
	 */
	public final TableField<PermissionRecord, String> PARENTID = createField("parentid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ewp.permission.ordernum</code>.
	 */
	public final TableField<PermissionRecord, Integer> ORDERNUM = createField("ordernum", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.permission.level</code>.
	 */
	public final TableField<PermissionRecord, Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.permission.orderby</code>.
	 */
	public final TableField<PermissionRecord, Integer> ORDERBY = createField("orderby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ewp.permission.action</code>.
	 */
	public final TableField<PermissionRecord, String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>ewp.permission</code> table reference
	 */
	public Permission() {
		this("permission", null);
	}

	/**
	 * Create an aliased <code>ewp.permission</code> table reference
	 */
	public Permission(String alias) {
		this(alias, PERMISSION);
	}

	private Permission(String alias, Table<PermissionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Permission(String alias, Table<PermissionRecord> aliased, Field<?>[] parameters) {
		super(alias, Ewp.EWP, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PermissionRecord> getPrimaryKey() {
		return Keys.KEY_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PermissionRecord>> getKeys() {
		return Arrays.<UniqueKey<PermissionRecord>>asList(Keys.KEY_PERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Permission as(String alias) {
		return new Permission(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Permission rename(String name) {
		return new Permission(name, null);
	}
}
